const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const DETAILS_SOURCE = fs.readFileSync(path.join(__dirname, "rfp-agent-chat-details.tsx"), "utf8");

test("RFP agent chat details render trigger editor states and run log links", () => {
	assert.doesNotMatch(DETAILS_SOURCE, /<DetailsSection title="Triggers">/u);
	assert.match(DETAILS_SOURCE, /function TriggerAddRow/u);
	assert.match(DETAILS_SOURCE, /const addTriggerControl = <TriggerAddRow \/>;/u);
	assert.match(DETAILS_SOURCE, /Status changed to/u);
	assert.match(DETAILS_SOURCE, /<TriggerChip>\{RFP_DRAFTING_COLUMN_NAME\}<\/TriggerChip>/u);
	assert.match(DETAILS_SOURCE, /<TriggerChip>\{RFP_DRAFTING_BOARD_NAME\}<\/TriggerChip>/u);
	assert.match(DETAILS_SOURCE, /aria-label="Delete trigger"/u);
	assert.match(DETAILS_SOURCE, /group-hover\/trigger-row:opacity-100/u);
	assert.match(DETAILS_SOURCE, /<span className="text-sm font-medium">\{label\}<\/span>/u);
	assert.match(DETAILS_SOURCE, /gap-2 text-sm text-text/u);
	assert.doesNotMatch(DETAILS_SOURCE, /Search triggers\.\.\./u);
	assert.doesNotMatch(DETAILS_SOURCE, /Ticket enters column/u);
	assert.doesNotMatch(DETAILS_SOURCE, /aria-label="Add trigger condition"/u);
	assert.doesNotMatch(DETAILS_SOURCE, /onClick=\{\(\) => setIsPickerOpen/u);
	assert.doesNotMatch(DETAILS_SOURCE, /<DetailsSection title="Agent Instructions">/u);
	assert.doesNotMatch(DETAILS_SOURCE, /PromptInput/u);
	assert.doesNotMatch(DETAILS_SOURCE, /Trigger natural language prompt/u);
	assert.doesNotMatch(DETAILS_SOURCE, /GPT-5\.5 Medium/u);
	assert.doesNotMatch(DETAILS_SOURCE, />\s*Save\s*<\/Button>/u);
	assert.doesNotMatch(DETAILS_SOURCE, /<DetailsSection title="Tasks">/u);
	assert.doesNotMatch(DETAILS_SOURCE, /<DetailsSection title="Skills">/u);
	assert.doesNotMatch(DETAILS_SOURCE, /<DetailsSection title="Tools">/u);
	assert.doesNotMatch(DETAILS_SOURCE, /<DetailsSection title="Knowledge">/u);
	assert.doesNotMatch(DETAILS_SOURCE, /Jira work item reader/u);
	assert.doesNotMatch(DETAILS_SOURCE, /RFP-101 approved report/u);
	assert.doesNotMatch(DETAILS_SOURCE, /Rerun policy: Completed tickets with draft output are skipped; failed tickets retry\./u);
	assert.match(DETAILS_SOURCE, /<DetailsSection title="Run log">/u);
	assert.match(DETAILS_SOURCE, /Processed \{run\.processedTicketCodes\.length\}/u);
	assert.match(DETAILS_SOURCE, /Skipped \{run\.skippedTicketCodes\.length\}/u);
	assert.match(DETAILS_SOURCE, /Failed \{run\.failedTicketCodes\.length\}/u);
	assert.match(DETAILS_SOURCE, /href=\{`\/rovo\/\$\{encodeURIComponent\(link\.threadId\)\}`\}/u);
	assert.doesNotMatch(DETAILS_SOURCE, /RfpAgentDetailsSheet/u);
	assert.doesNotMatch(DETAILS_SOURCE, /SheetContent/u);
	assert.doesNotMatch(DETAILS_SOURCE, /Weekdays at 9:00 AM/u);
	assert.doesNotMatch(DETAILS_SOURCE, /Approval required/u);
});
