import { TEMPLATE_IDS } from "../schemas/render-payload.schema.mjs";

const DEFINITIONS = [
	{
		id: "exploration-code-approaches",
		family: "html-effectiveness",
		category: "Exploration & Planning",
		label: "Code Approaches",
		interaction: "tabs",
		print: true,
		description: "Compare implementation approaches and recommend one path.",
	},
	{
		id: "exploration-visual-designs",
		family: "html-effectiveness",
		category: "Exploration & Planning",
		label: "Visual Directions",
		interaction: "variant-switcher",
		print: true,
		description: "Compare visual directions and interaction tone.",
	},
	{
		id: "implementation-plan",
		family: "html-effectiveness",
		category: "Exploration & Planning",
		label: "Implementation Plan",
		interaction: "collapsible-milestones",
		print: true,
		description: "Plan milestones, risks, validation gates, and ownership.",
	},
	{
		id: "code-review-pr",
		family: "html-effectiveness",
		category: "Code Review & Understanding",
		label: "Annotated Pull Request",
		interaction: "filters",
		print: true,
		description: "Summarize findings, evidence, and reviewer focus.",
	},
	{
		id: "pr-writeup",
		family: "html-effectiveness",
		category: "Code Review & Understanding",
		label: "PR Writeup",
		interaction: "static",
		print: true,
		description: "Prepare a concise PR handoff for reviewers.",
	},
	{
		id: "code-understanding",
		family: "html-effectiveness",
		category: "Code Review & Understanding",
		label: "Code Understanding",
		interaction: "highlighted-path",
		print: true,
		description: "Explain a module map, data flow, or code path.",
	},
	{
		id: "design-system",
		family: "html-effectiveness",
		category: "Design",
		label: "Design System",
		interaction: "copyable-token-swatches",
		print: true,
		description: "Document tokens, components, and design rules.",
	},
	{
		id: "component-variants",
		family: "html-effectiveness",
		category: "Design",
		label: "Component Variants",
		interaction: "state-filters",
		print: true,
		description: "Show component variants, states, and notes.",
	},
	{
		id: "prototype-animation",
		family: "html-effectiveness",
		category: "Prototyping",
		label: "Animation Prototype",
		interaction: "sliders",
		print: false,
		description: "Tune motion values with inline slider controls.",
	},
	{
		id: "prototype-interaction",
		family: "html-effectiveness",
		category: "Prototyping",
		label: "Interaction Prototype",
		interaction: "step-navigation",
		print: false,
		description: "Navigate a clickable flow with keyboard support.",
	},
	{
		id: "svg-illustrations",
		family: "html-effectiveness",
		category: "Illustrations & Diagrams",
		label: "SVG Illustrations",
		interaction: "copy-select",
		print: true,
		description: "Render a reusable inline SVG figure sheet.",
	},
	{
		id: "flowchart-diagram",
		family: "html-effectiveness",
		category: "Illustrations & Diagrams",
		label: "Flowchart Diagram",
		interaction: "step-details",
		print: true,
		description: "Show an annotated flowchart with explanatory notes.",
	},
	{
		id: "slide-deck",
		family: "html-effectiveness",
		category: "Decks",
		label: "Slide Deck",
		interaction: "keyboard-deck",
		print: true,
		description: "Browser-first deck with arrow-key navigation and print styles.",
	},
	{
		id: "research-feature-explainer",
		family: "html-effectiveness",
		category: "Research & Learning",
		label: "Feature Explainer",
		interaction: "collapsible-sections",
		print: true,
		description: "Explain how a product or technical feature works.",
	},
	{
		id: "research-concept-explainer",
		family: "html-effectiveness",
		category: "Research & Learning",
		label: "Concept Explainer",
		interaction: "optional-diagram",
		print: true,
		description: "Explain a concept with intuition, examples, and evidence.",
	},
	{
		id: "status-report",
		family: "html-effectiveness",
		category: "Reports",
		label: "Status Report",
		interaction: "static",
		print: true,
		description: "Summarize project status, changes, and next actions.",
	},
	{
		id: "incident-report",
		family: "html-effectiveness",
		category: "Reports",
		label: "Incident Report",
		interaction: "timeline-navigation",
		print: true,
		description: "Document incident impact, timeline, causes, and follow-ups.",
	},
	{
		id: "editor-triage-board",
		family: "html-effectiveness",
		category: "Custom Editors",
		label: "Triage Board",
		interaction: "keyboard-reorder",
		print: false,
		description: "Create a keyboard-operable ticket triage board.",
	},
	{
		id: "editor-feature-flags",
		family: "html-effectiveness",
		category: "Custom Editors",
		label: "Feature Flags",
		interaction: "toggles-and-export",
		print: false,
		description: "Edit feature flag states and export JSON.",
	},
	{
		id: "editor-prompt-tuner",
		family: "html-effectiveness",
		category: "Custom Editors",
		label: "Prompt Tuner",
		interaction: "live-preview",
		print: false,
		description: "Tune prompts with a live preview and export controls.",
	},
	{
		id: "one-pager",
		family: "print",
		category: "Kami Print & Business",
		label: "One Pager",
		interaction: "static",
		print: true,
		description: "Compact executive summary, proposal, or briefing.",
	},
	{
		id: "long-doc",
		family: "print",
		category: "Kami Print & Business",
		label: "Long Document",
		interaction: "static",
		print: true,
		description: "Long-form editorial chapter, report, or essay.",
	},
	{
		id: "letter",
		family: "print",
		category: "Kami Print & Business",
		label: "Letter",
		interaction: "static",
		print: true,
		description: "Formal letter, memo, or recommendation.",
	},
	{
		id: "portfolio",
		family: "print",
		category: "Kami Print & Business",
		label: "Portfolio",
		interaction: "static",
		print: true,
		description: "Case studies and work samples.",
	},
	{
		id: "resume",
		family: "print",
		category: "Kami Print & Business",
		label: "Resume",
		interaction: "static",
		print: true,
		description: "Resume or CV with data-first bullets.",
	},
	{
		id: "equity-report",
		family: "print",
		category: "Kami Print & Business",
		label: "Equity Report",
		interaction: "static",
		print: true,
		description: "Investment memo or valuation note with sourced claims.",
	},
	{
		id: "changelog",
		family: "print",
		category: "Kami Print & Business",
		label: "Changelog",
		interaction: "static",
		print: true,
		description: "Styled release notes or changelog.",
	},
	{
		id: "math-knowledge",
		family: "math",
		category: "Math Knowledge",
		label: "Math Knowledge",
		interaction: "concept-graph",
		print: true,
		description: "Concept page with definitions, intuition, examples, notation, and prerequisites.",
	},
	{
		id: "math-proof",
		family: "math",
		category: "Math Knowledge",
		label: "Math Proof",
		interaction: "step-reveal",
		print: true,
		description: "Proof walkthrough with assumptions and transformations.",
	},
	{
		id: "math-procedure",
		family: "math",
		category: "Math Knowledge",
		label: "Math Procedure",
		interaction: "decision-points",
		print: true,
		description: "Worked method or algorithm with common mistakes.",
	},
	{
		id: "math-handout",
		family: "math",
		category: "Math Knowledge",
		label: "Math Handout",
		interaction: "static",
		print: true,
		description: "Print-friendly learning sheet with exercises and answers.",
	},
	{
		id: "math-concept-map",
		family: "math",
		category: "Math Knowledge",
		label: "Math Concept Map",
		interaction: "graph",
		print: true,
		description: "Prerequisite graph or relationship map.",
	},
	{
		id: "math-interactive",
		family: "math",
		category: "Math Knowledge",
		label: "Math Interactive",
		interaction: "inline-svg-js",
		print: false,
		description: "Manipulable math concept demo.",
	},
];

const definitionIds = DEFINITIONS.map(definition => definition.id);
const missing = TEMPLATE_IDS.filter(id => !definitionIds.includes(id));
const extra = definitionIds.filter(id => !TEMPLATE_IDS.includes(id));

if (missing.length > 0 || extra.length > 0) {
	throw new Error(
		`Template catalog mismatch. Missing: ${missing.join(", ") || "none"}; extra: ${
			extra.join(", ") || "none"
		}`,
	);
}

export const TEMPLATE_DEFINITIONS = DEFINITIONS;
export const TEMPLATE_DEFINITION_BY_ID = Object.fromEntries(
	DEFINITIONS.map(definition => [definition.id, definition]),
);

export function getTemplateDefinition(templateId) {
	const definition = TEMPLATE_DEFINITION_BY_ID[templateId];
	if (!definition) throw new Error(`Unknown template: ${templateId}`);
	return definition;
}

export function listTemplatesByFamily(family) {
	return TEMPLATE_DEFINITIONS.filter(definition => definition.family === family);
}
