// Auto-generated by scripts/generate-icon-registry.js — do not edit manually
import type { NewCoreIconProps } from "@atlaskit/icon/base-new";

import AccessibilityIcon from "@atlaskit/icon/core/accessibility";
import AddIcon from "@atlaskit/icon/core/add";
import AiAgentIcon from "@atlaskit/icon/core/ai-agent";
import AiChatIcon from "@atlaskit/icon/core/ai-chat";
import AiGenerativeTextSummaryIcon from "@atlaskit/icon/core/ai-generative-text-summary";
import AiSparkleIcon from "@atlaskit/icon/core/ai-sparkle";
import AlertIcon from "@atlaskit/icon/core/alert";
import AlignImageCenterIcon from "@atlaskit/icon/core/align-image-center";
import AlignImageLeftIcon from "@atlaskit/icon/core/align-image-left";
import AlignImageRightIcon from "@atlaskit/icon/core/align-image-right";
import AlignTextCenterIcon from "@atlaskit/icon/core/align-text-center";
import AlignTextLeftIcon from "@atlaskit/icon/core/align-text-left";
import AlignTextRightIcon from "@atlaskit/icon/core/align-text-right";
import AngleBracketsIcon from "@atlaskit/icon/core/angle-brackets";
import ApiIcon from "@atlaskit/icon/core/api";
import AppIcon from "@atlaskit/icon/core/app";
import AppSwitcherIcon from "@atlaskit/icon/core/app-switcher";
import AppSwitcherLegacyIcon from "@atlaskit/icon/core/app-switcher-legacy";
import AppsIcon from "@atlaskit/icon/core/apps";
import ArchiveBoxIcon from "@atlaskit/icon/core/archive-box";
import ArrowDownIcon from "@atlaskit/icon/core/arrow-down";
import ArrowDownLeftIcon from "@atlaskit/icon/core/arrow-down-left";
import ArrowDownRightIcon from "@atlaskit/icon/core/arrow-down-right";
import ArrowLeftIcon from "@atlaskit/icon/core/arrow-left";
import ArrowRightIcon from "@atlaskit/icon/core/arrow-right";
import ArrowUpIcon from "@atlaskit/icon/core/arrow-up";
import ArrowUpLeftIcon from "@atlaskit/icon/core/arrow-up-left";
import ArrowUpRightIcon from "@atlaskit/icon/core/arrow-up-right";
import AssetsIcon from "@atlaskit/icon/core/assets";
import AtlassianIntelligenceIcon from "@atlaskit/icon/core/atlassian-intelligence";
import AttachmentIcon from "@atlaskit/icon/core/attachment";
import AudioIcon from "@atlaskit/icon/core/audio";
import AutomationIcon from "@atlaskit/icon/core/automation";
import BacklogIcon from "@atlaskit/icon/core/backlog";
import BasketballIcon from "@atlaskit/icon/core/basketball";
import BoardIcon from "@atlaskit/icon/core/board";
import BoardsIcon from "@atlaskit/icon/core/boards";
import BookWithBookmarkIcon from "@atlaskit/icon/core/book-with-bookmark";
import BorderIcon from "@atlaskit/icon/core/border";
import BranchIcon from "@atlaskit/icon/core/branch";
import BriefcaseIcon from "@atlaskit/icon/core/briefcase";
import BugIcon from "@atlaskit/icon/core/bug";
import CalendarIcon from "@atlaskit/icon/core/calendar";
import CalendarPlusIcon from "@atlaskit/icon/core/calendar-plus";
import CameraIcon from "@atlaskit/icon/core/camera";
import CaptureIcon from "@atlaskit/icon/core/capture";
import CardIcon from "@atlaskit/icon/core/card";
import CashIcon from "@atlaskit/icon/core/cash";
import ChangesIcon from "@atlaskit/icon/core/changes";
import ChartBarIcon from "@atlaskit/icon/core/chart-bar";
import ChartBubbleIcon from "@atlaskit/icon/core/chart-bubble";
import ChartMatrixIcon from "@atlaskit/icon/core/chart-matrix";
import ChartPieIcon from "@atlaskit/icon/core/chart-pie";
import ChartTrendIcon from "@atlaskit/icon/core/chart-trend";
import ChartTrendDownIcon from "@atlaskit/icon/core/chart-trend-down";
import ChartTrendUpIcon from "@atlaskit/icon/core/chart-trend-up";
import ChatWidgetIcon from "@atlaskit/icon/core/chat-widget";
import CheckCircleIcon from "@atlaskit/icon/core/check-circle";
import CheckCircleUncheckedIcon from "@atlaskit/icon/core/check-circle-unchecked";
import CheckMarkIcon from "@atlaskit/icon/core/check-mark";
import CheckboxCheckedIcon from "@atlaskit/icon/core/checkbox-checked";
import CheckboxIndeterminateIcon from "@atlaskit/icon/core/checkbox-indeterminate";
import CheckboxUncheckedIcon from "@atlaskit/icon/core/checkbox-unchecked";
import ChevronDoubleLeftIcon from "@atlaskit/icon/core/chevron-double-left";
import ChevronDoubleRightIcon from "@atlaskit/icon/core/chevron-double-right";
import ChevronDownIcon from "@atlaskit/icon/core/chevron-down";
import ChevronLeftIcon from "@atlaskit/icon/core/chevron-left";
import ChevronRightIcon from "@atlaskit/icon/core/chevron-right";
import ChevronUpIcon from "@atlaskit/icon/core/chevron-up";
import ChildWorkItemsIcon from "@atlaskit/icon/core/child-work-items";
import ClipboardIcon from "@atlaskit/icon/core/clipboard";
import ClockIcon from "@atlaskit/icon/core/clock";
import CloseIcon from "@atlaskit/icon/core/close";
import CloudArrowUpIcon from "@atlaskit/icon/core/cloud-arrow-up";
import CollapseHorizontalIcon from "@atlaskit/icon/core/collapse-horizontal";
import CollapseVerticalIcon from "@atlaskit/icon/core/collapse-vertical";
import CommentIcon from "@atlaskit/icon/core/comment";
import CommentAddIcon from "@atlaskit/icon/core/comment-add";
import CommitIcon from "@atlaskit/icon/core/commit";
import CompassIcon from "@atlaskit/icon/core/compass";
import ComponentIcon from "@atlaskit/icon/core/component";
import ContentWidthNarrowIcon from "@atlaskit/icon/core/content-width-narrow";
import ContentWidthWideIcon from "@atlaskit/icon/core/content-width-wide";
import ContentWrapLeftIcon from "@atlaskit/icon/core/content-wrap-left";
import ContentWrapRightIcon from "@atlaskit/icon/core/content-wrap-right";
import CopyIcon from "@atlaskit/icon/core/copy";
import CreditCardIcon from "@atlaskit/icon/core/credit-card";
import CrossIcon from "@atlaskit/icon/core/cross";
import CrossCircleIcon from "@atlaskit/icon/core/cross-circle";
import CurlyBracketsIcon from "@atlaskit/icon/core/curly-brackets";
import CustomizeIcon from "@atlaskit/icon/core/customize";
import DashboardIcon from "@atlaskit/icon/core/dashboard";
import DataFlowIcon from "@atlaskit/icon/core/data-flow";
import DataNumberIcon from "@atlaskit/icon/core/data-number";
import DataStringIcon from "@atlaskit/icon/core/data-string";
import DatabaseIcon from "@atlaskit/icon/core/database";
import DecisionIcon from "@atlaskit/icon/core/decision";
import DefectIcon from "@atlaskit/icon/core/defect";
import DeleteIcon from "@atlaskit/icon/core/delete";
import DepartmentIcon from "@atlaskit/icon/core/department";
import DeviceMobileIcon from "@atlaskit/icon/core/device-mobile";
import DevicesIcon from "@atlaskit/icon/core/devices";
import DiscoveryIcon from "@atlaskit/icon/core/discovery";
import DownloadIcon from "@atlaskit/icon/core/download";
import DragHandleHorizontalIcon from "@atlaskit/icon/core/drag-handle-horizontal";
import DragHandleVerticalIcon from "@atlaskit/icon/core/drag-handle-vertical";
import EditIcon from "@atlaskit/icon/core/edit";
import EditBulkIcon from "@atlaskit/icon/core/edit-bulk";
import EmailIcon from "@atlaskit/icon/core/email";
import EmojiIcon from "@atlaskit/icon/core/emoji";
import EmojiAddIcon from "@atlaskit/icon/core/emoji-add";
import EmojiCasualIcon from "@atlaskit/icon/core/emoji-casual";
import EmojiNeutralIcon from "@atlaskit/icon/core/emoji-neutral";
import EmojiRemoveIcon from "@atlaskit/icon/core/emoji-remove";
import EpicIcon from "@atlaskit/icon/core/epic";
import ErrorIcon from "@atlaskit/icon/core/error";
import ExclamationSquareIcon from "@atlaskit/icon/core/exclamation-square";
import ExpandHorizontalIcon from "@atlaskit/icon/core/expand-horizontal";
import ExpandVerticalIcon from "@atlaskit/icon/core/expand-vertical";
import EyeOpenIcon from "@atlaskit/icon/core/eye-open";
import EyeOpenFilledIcon from "@atlaskit/icon/core/eye-open-filled";
import EyeOpenStrikethroughIcon from "@atlaskit/icon/core/eye-open-strikethrough";
import FeedIcon from "@atlaskit/icon/core/feed";
import FeedbackIcon from "@atlaskit/icon/core/feedback";
import FieldIcon from "@atlaskit/icon/core/field";
import FieldAlertIcon from "@atlaskit/icon/core/field-alert";
import FieldCheckboxGroupIcon from "@atlaskit/icon/core/field-checkbox-group";
import FieldDropdownIcon from "@atlaskit/icon/core/field-dropdown";
import FieldRadioGroupIcon from "@atlaskit/icon/core/field-radio-group";
import FileIcon from "@atlaskit/icon/core/file";
import FilesIcon from "@atlaskit/icon/core/files";
import FilterIcon from "@atlaskit/icon/core/filter";
import FlagIcon from "@atlaskit/icon/core/flag";
import FlagFilledIcon from "@atlaskit/icon/core/flag-filled";
import FlaskIcon from "@atlaskit/icon/core/flask";
import FocusAreaIcon from "@atlaskit/icon/core/focus-area";
import FolderClosedIcon from "@atlaskit/icon/core/folder-closed";
import FolderOpenIcon from "@atlaskit/icon/core/folder-open";
import FormIcon from "@atlaskit/icon/core/form";
import FullscreenEnterIcon from "@atlaskit/icon/core/fullscreen-enter";
import FullscreenExitIcon from "@atlaskit/icon/core/fullscreen-exit";
import GlassesIcon from "@atlaskit/icon/core/glasses";
import GlobeIcon from "@atlaskit/icon/core/globe";
import GoalIcon from "@atlaskit/icon/core/goal";
import GridIcon from "@atlaskit/icon/core/grid";
import GrowDiagonalIcon from "@atlaskit/icon/core/grow-diagonal";
import GrowHorizontalIcon from "@atlaskit/icon/core/grow-horizontal";
import GrowVerticalIcon from "@atlaskit/icon/core/grow-vertical";
import HashtagIcon from "@atlaskit/icon/core/hashtag";
import HeadphonesIcon from "@atlaskit/icon/core/headphones";
import HeartIcon from "@atlaskit/icon/core/heart";
import HighlightIcon from "@atlaskit/icon/core/highlight";
import HomeIcon from "@atlaskit/icon/core/home";
import ImageIcon from "@atlaskit/icon/core/image";
import ImageFullscreenIcon from "@atlaskit/icon/core/image-fullscreen";
import ImageInlineIcon from "@atlaskit/icon/core/image-inline";
import ImageScaledIcon from "@atlaskit/icon/core/image-scaled";
import InboxIcon from "@atlaskit/icon/core/inbox";
import IncidentIcon from "@atlaskit/icon/core/incident";
import InformationIcon from "@atlaskit/icon/core/information";
import InformationCircleIcon from "@atlaskit/icon/core/information-circle";
import KeyResultIcon from "@atlaskit/icon/core/key-result";
import LayoutOneColumnIcon from "@atlaskit/icon/core/layout-one-column";
import LayoutThreeColumnsIcon from "@atlaskit/icon/core/layout-three-columns";
import LayoutThreeColumnsSidebarsIcon from "@atlaskit/icon/core/layout-three-columns-sidebars";
import LayoutTwoColumnsIcon from "@atlaskit/icon/core/layout-two-columns";
import LayoutTwoColumnsSidebarLeftIcon from "@atlaskit/icon/core/layout-two-columns-sidebar-left";
import LayoutTwoColumnsSidebarRightIcon from "@atlaskit/icon/core/layout-two-columns-sidebar-right";
import LibraryIcon from "@atlaskit/icon/core/library";
import LightbulbIcon from "@atlaskit/icon/core/lightbulb";
import LinkIcon from "@atlaskit/icon/core/link";
import LinkBrokenIcon from "@atlaskit/icon/core/link-broken";
import LinkExternalIcon from "@atlaskit/icon/core/link-external";
import ListBulletedIcon from "@atlaskit/icon/core/list-bulleted";
import ListChecklistIcon from "@atlaskit/icon/core/list-checklist";
import ListNumberedIcon from "@atlaskit/icon/core/list-numbered";
import LobbyBellIcon from "@atlaskit/icon/core/lobby-bell";
import LocationIcon from "@atlaskit/icon/core/location";
import LockLockedIcon from "@atlaskit/icon/core/lock-locked";
import LockUnlockedIcon from "@atlaskit/icon/core/lock-unlocked";
import LogInIcon from "@atlaskit/icon/core/log-in";
import LogOutIcon from "@atlaskit/icon/core/log-out";
import MagicWandIcon from "@atlaskit/icon/core/magic-wand";
import MarkdownIcon from "@atlaskit/icon/core/markdown";
import MarketplaceIcon from "@atlaskit/icon/core/marketplace";
import MaximizeIcon from "@atlaskit/icon/core/maximize";
import MegaphoneIcon from "@atlaskit/icon/core/megaphone";
import MentionIcon from "@atlaskit/icon/core/mention";
import MenuIcon from "@atlaskit/icon/core/menu";
import MergeFailureIcon from "@atlaskit/icon/core/merge-failure";
import MergeSuccessIcon from "@atlaskit/icon/core/merge-success";
import MicrophoneIcon from "@atlaskit/icon/core/microphone";
import MinimizeIcon from "@atlaskit/icon/core/minimize";
import MinusIcon from "@atlaskit/icon/core/minus";
import MinusSquareIcon from "@atlaskit/icon/core/minus-square";
import NodeIcon from "@atlaskit/icon/core/node";
import NoteIcon from "@atlaskit/icon/core/note";
import NotificationIcon from "@atlaskit/icon/core/notification";
import NotificationMutedIcon from "@atlaskit/icon/core/notification-muted";
import ObjectiveIcon from "@atlaskit/icon/core/objective";
import OfficeBuildingIcon from "@atlaskit/icon/core/office-building";
import OnCallIcon from "@atlaskit/icon/core/on-call";
import OperationsIcon from "@atlaskit/icon/core/operations";
import PageIcon from "@atlaskit/icon/core/page";
import PagesIcon from "@atlaskit/icon/core/pages";
import PaintBucketIcon from "@atlaskit/icon/core/paint-bucket";
import PaintPaletteIcon from "@atlaskit/icon/core/paint-palette";
import PanelLeftIcon from "@atlaskit/icon/core/panel-left";
import PanelRightIcon from "@atlaskit/icon/core/panel-right";
import PenIcon from "@atlaskit/icon/core/pen";
import PeopleGroupIcon from "@atlaskit/icon/core/people-group";
import PersonIcon from "@atlaskit/icon/core/person";
import PersonAddIcon from "@atlaskit/icon/core/person-add";
import PersonAddedIcon from "@atlaskit/icon/core/person-added";
import PersonAvatarIcon from "@atlaskit/icon/core/person-avatar";
import PersonOffboardIcon from "@atlaskit/icon/core/person-offboard";
import PersonRemoveIcon from "@atlaskit/icon/core/person-remove";
import PersonWarningIcon from "@atlaskit/icon/core/person-warning";
import PhoneIcon from "@atlaskit/icon/core/phone";
import PinIcon from "@atlaskit/icon/core/pin";
import PinFilledIcon from "@atlaskit/icon/core/pin-filled";
import PlusSquareIcon from "@atlaskit/icon/core/plus-square";
import PowerPlugIcon from "@atlaskit/icon/core/power-plug";
import PremiumIcon from "@atlaskit/icon/core/premium";
import PresenterModeIcon from "@atlaskit/icon/core/presenter-mode";
import PrinterIcon from "@atlaskit/icon/core/printer";
import PriorityBlockerIcon from "@atlaskit/icon/core/priority-blocker";
import PriorityCriticalIcon from "@atlaskit/icon/core/priority-critical";
import PriorityHighIcon from "@atlaskit/icon/core/priority-high";
import PriorityHighestIcon from "@atlaskit/icon/core/priority-highest";
import PriorityLowIcon from "@atlaskit/icon/core/priority-low";
import PriorityLowestIcon from "@atlaskit/icon/core/priority-lowest";
import PriorityMajorIcon from "@atlaskit/icon/core/priority-major";
import PriorityMediumIcon from "@atlaskit/icon/core/priority-medium";
import PriorityMinorIcon from "@atlaskit/icon/core/priority-minor";
import PriorityTrivialIcon from "@atlaskit/icon/core/priority-trivial";
import ProblemIcon from "@atlaskit/icon/core/problem";
import ProjectIcon from "@atlaskit/icon/core/project";
import ProjectStatusIcon from "@atlaskit/icon/core/project-status";
import ProjectionScreenIcon from "@atlaskit/icon/core/projection-screen";
import PullRequestIcon from "@atlaskit/icon/core/pull-request";
import PulseIcon from "@atlaskit/icon/core/pulse";
import QuestionCircleIcon from "@atlaskit/icon/core/question-circle";
import QuotationMarkIcon from "@atlaskit/icon/core/quotation-mark";
import RadioCheckedIcon from "@atlaskit/icon/core/radio-checked";
import RadioUncheckedIcon from "@atlaskit/icon/core/radio-unchecked";
import RedoIcon from "@atlaskit/icon/core/redo";
import RefreshIcon from "@atlaskit/icon/core/refresh";
import ReleaseIcon from "@atlaskit/icon/core/release";
import RetryIcon from "@atlaskit/icon/core/retry";
import RoadmapIcon from "@atlaskit/icon/core/roadmap";
import RovoChatIcon from "@atlaskit/icon/core/rovo-chat";
import ScalesIcon from "@atlaskit/icon/core/scales";
import ScorecardIcon from "@atlaskit/icon/core/scorecard";
import ScreenIcon from "@atlaskit/icon/core/screen";
import ScreenPlusIcon from "@atlaskit/icon/core/screen-plus";
import SearchIcon from "@atlaskit/icon/core/search";
import SendIcon from "@atlaskit/icon/core/send";
import SettingsIcon from "@atlaskit/icon/core/settings";
import ShapesIcon from "@atlaskit/icon/core/shapes";
import ShareIcon from "@atlaskit/icon/core/share";
import ShieldIcon from "@atlaskit/icon/core/shield";
import ShieldStrikethroughIcon from "@atlaskit/icon/core/shield-strikethrough";
import ShortcutIcon from "@atlaskit/icon/core/shortcut";
import ShowMoreHorizontalIcon from "@atlaskit/icon/core/show-more-horizontal";
import ShowMoreVerticalIcon from "@atlaskit/icon/core/show-more-vertical";
import ShrinkDiagonalIcon from "@atlaskit/icon/core/shrink-diagonal";
import ShrinkHorizontalIcon from "@atlaskit/icon/core/shrink-horizontal";
import ShrinkVerticalIcon from "@atlaskit/icon/core/shrink-vertical";
import SidebarCollapseIcon from "@atlaskit/icon/core/sidebar-collapse";
import SidebarExpandIcon from "@atlaskit/icon/core/sidebar-expand";
import SmartLinkIcon from "@atlaskit/icon/core/smart-link";
import SmartLinkCardIcon from "@atlaskit/icon/core/smart-link-card";
import SmartLinkEmbedIcon from "@atlaskit/icon/core/smart-link-embed";
import SmartLinkInlineIcon from "@atlaskit/icon/core/smart-link-inline";
import SmartLinkListIcon from "@atlaskit/icon/core/smart-link-list";
import SnippetIcon from "@atlaskit/icon/core/snippet";
import SortAscendingIcon from "@atlaskit/icon/core/sort-ascending";
import SortDescendingIcon from "@atlaskit/icon/core/sort-descending";
import SpreadsheetIcon from "@atlaskit/icon/core/spreadsheet";
import SprintIcon from "@atlaskit/icon/core/sprint";
import StarStarredIcon from "@atlaskit/icon/core/star-starred";
import StarUnstarredIcon from "@atlaskit/icon/core/star-unstarred";
import StatusDiscoveryIcon from "@atlaskit/icon/core/status-discovery";
import StatusErrorIcon from "@atlaskit/icon/core/status-error";
import StatusInformationIcon from "@atlaskit/icon/core/status-information";
import StatusSuccessIcon from "@atlaskit/icon/core/status-success";
import StatusVerifiedIcon from "@atlaskit/icon/core/status-verified";
import StatusWarningIcon from "@atlaskit/icon/core/status-warning";
import StopwatchIcon from "@atlaskit/icon/core/stopwatch";
import StoryIcon from "@atlaskit/icon/core/story";
import StrokeWeightExtraLargeIcon from "@atlaskit/icon/core/stroke-weight-extra-large";
import StrokeWeightLargeIcon from "@atlaskit/icon/core/stroke-weight-large";
import StrokeWeightMediumIcon from "@atlaskit/icon/core/stroke-weight-medium";
import StrokeWeightSmallIcon from "@atlaskit/icon/core/stroke-weight-small";
import SubtasksIcon from "@atlaskit/icon/core/subtasks";
import SuccessIcon from "@atlaskit/icon/core/success";
import SupportIcon from "@atlaskit/icon/core/support";
import TableIcon from "@atlaskit/icon/core/table";
import TableCellClearIcon from "@atlaskit/icon/core/table-cell-clear";
import TableCellMergeIcon from "@atlaskit/icon/core/table-cell-merge";
import TableCellSplitIcon from "@atlaskit/icon/core/table-cell-split";
import TableColumnAddLeftIcon from "@atlaskit/icon/core/table-column-add-left";
import TableColumnAddRightIcon from "@atlaskit/icon/core/table-column-add-right";
import TableColumnDeleteIcon from "@atlaskit/icon/core/table-column-delete";
import TableColumnMoveLeftIcon from "@atlaskit/icon/core/table-column-move-left";
import TableColumnMoveRightIcon from "@atlaskit/icon/core/table-column-move-right";
import TableColumnsDistributeIcon from "@atlaskit/icon/core/table-columns-distribute";
import TableRowAddAboveIcon from "@atlaskit/icon/core/table-row-add-above";
import TableRowAddBelowIcon from "@atlaskit/icon/core/table-row-add-below";
import TableRowDeleteIcon from "@atlaskit/icon/core/table-row-delete";
import TableRowMoveDownIcon from "@atlaskit/icon/core/table-row-move-down";
import TableRowMoveUpIcon from "@atlaskit/icon/core/table-row-move-up";
import TagIcon from "@atlaskit/icon/core/tag";
import TakeoutFoodIcon from "@atlaskit/icon/core/takeout-food";
import TargetIcon from "@atlaskit/icon/core/target";
import TaskIcon from "@atlaskit/icon/core/task";
import TaskInProgressIcon from "@atlaskit/icon/core/task-in-progress";
import TaskToDoIcon from "@atlaskit/icon/core/task-to-do";
import TasksIcon from "@atlaskit/icon/core/tasks";
import TeamsIcon from "@atlaskit/icon/core/teams";
import TextIcon from "@atlaskit/icon/core/text";
import TextBoldIcon from "@atlaskit/icon/core/text-bold";
import TextHeadingIcon from "@atlaskit/icon/core/text-heading";
import TextIndentLeftIcon from "@atlaskit/icon/core/text-indent-left";
import TextIndentRightIcon from "@atlaskit/icon/core/text-indent-right";
import TextItalicIcon from "@atlaskit/icon/core/text-italic";
import TextShortenIcon from "@atlaskit/icon/core/text-shorten";
import TextSpellcheckIcon from "@atlaskit/icon/core/text-spellcheck";
import TextStrikethroughIcon from "@atlaskit/icon/core/text-strikethrough";
import TextStyleIcon from "@atlaskit/icon/core/text-style";
import TextUnderlineIcon from "@atlaskit/icon/core/text-underline";
import TextWrapIcon from "@atlaskit/icon/core/text-wrap";
import ThemeIcon from "@atlaskit/icon/core/theme";
import ThumbsDownIcon from "@atlaskit/icon/core/thumbs-down";
import ThumbsUpIcon from "@atlaskit/icon/core/thumbs-up";
import TimelineIcon from "@atlaskit/icon/core/timeline";
import ToolsIcon from "@atlaskit/icon/core/tools";
import TransitionIcon from "@atlaskit/icon/core/transition";
import TranslateIcon from "@atlaskit/icon/core/translate";
import TreeIcon from "@atlaskit/icon/core/tree";
import UndoIcon from "@atlaskit/icon/core/undo";
import UploadIcon from "@atlaskit/icon/core/upload";
import VehicleCarIcon from "@atlaskit/icon/core/vehicle-car";
import VideoIcon from "@atlaskit/icon/core/video";
import VideoNextIcon from "@atlaskit/icon/core/video-next";
import VideoNextOverlayIcon from "@atlaskit/icon/core/video-next-overlay";
import VideoPauseIcon from "@atlaskit/icon/core/video-pause";
import VideoPauseOverlayIcon from "@atlaskit/icon/core/video-pause-overlay";
import VideoPlayIcon from "@atlaskit/icon/core/video-play";
import VideoPlayOverlayIcon from "@atlaskit/icon/core/video-play-overlay";
import VideoPreviousIcon from "@atlaskit/icon/core/video-previous";
import VideoPreviousOverlayIcon from "@atlaskit/icon/core/video-previous-overlay";
import VideoSkipBackwardFifteenIcon from "@atlaskit/icon/core/video-skip-backward-fifteen";
import VideoSkipBackwardTenIcon from "@atlaskit/icon/core/video-skip-backward-ten";
import VideoSkipForwardFifteenIcon from "@atlaskit/icon/core/video-skip-forward-fifteen";
import VideoSkipForwardTenIcon from "@atlaskit/icon/core/video-skip-forward-ten";
import VideoStopIcon from "@atlaskit/icon/core/video-stop";
import VideoStopOverlayIcon from "@atlaskit/icon/core/video-stop-overlay";
import VolumeHighIcon from "@atlaskit/icon/core/volume-high";
import VolumeLowIcon from "@atlaskit/icon/core/volume-low";
import VolumeMutedIcon from "@atlaskit/icon/core/volume-muted";
import WarningIcon from "@atlaskit/icon/core/warning";
import WhiteboardIcon from "@atlaskit/icon/core/whiteboard";
import WorkItemIcon from "@atlaskit/icon/core/work-item";
import WorkItemsIcon from "@atlaskit/icon/core/work-items";
import ZoomInIcon from "@atlaskit/icon/core/zoom-in";
import ZoomOutIcon from "@atlaskit/icon/core/zoom-out";
import LabAiBotIcon from "@atlaskit/icon-lab/core/ai-bot";
import LabAiComputeIcon from "@atlaskit/icon-lab/core/ai-compute";
import LabAiGenerativeAudioBriefingIcon from "@atlaskit/icon-lab/core/ai-generative-audio-briefing";
import LabAiGenerativeChaptersIcon from "@atlaskit/icon-lab/core/ai-generative-chapters";
import LabAiGenerativeCleanupIcon from "@atlaskit/icon-lab/core/ai-generative-cleanup";
import LabAiGenerativeRemoveIcon from "@atlaskit/icon-lab/core/ai-generative-remove";
import LabAiGenerativeRemoveSilenceIcon from "@atlaskit/icon-lab/core/ai-generative-remove-silence";
import LabAiGenerativeTextIcon from "@atlaskit/icon-lab/core/ai-generative-text";
import LabAiGenerativeTextTitleIcon from "@atlaskit/icon-lab/core/ai-generative-text-title";
import LabAiModelIcon from "@atlaskit/icon-lab/core/ai-model";
import LabAiSearchIcon from "@atlaskit/icon-lab/core/ai-search";
import LabArrowCurvedDownLeftIcon from "@atlaskit/icon-lab/core/arrow-curved-down-left";
import LabArrowCurvedDownRightIcon from "@atlaskit/icon-lab/core/arrow-curved-down-right";
import LabArrowCurvedLeftDownIcon from "@atlaskit/icon-lab/core/arrow-curved-left-down";
import LabArrowCurvedLeftUpIcon from "@atlaskit/icon-lab/core/arrow-curved-left-up";
import LabArrowCurvedRightDownIcon from "@atlaskit/icon-lab/core/arrow-curved-right-down";
import LabArrowCurvedRightUpIcon from "@atlaskit/icon-lab/core/arrow-curved-right-up";
import LabArrowCurvedUpLeftIcon from "@atlaskit/icon-lab/core/arrow-curved-up-left";
import LabArrowCurvedUpRightIcon from "@atlaskit/icon-lab/core/arrow-curved-up-right";
import LabArrowEndIcon from "@atlaskit/icon-lab/core/arrow-end";
import LabArrowStartIcon from "@atlaskit/icon-lab/core/arrow-start";
import LabArrowsDiagonalUpRightDownLeftIcon from "@atlaskit/icon-lab/core/arrows-diagonal-up-right-down-left";
import LabAskIcon from "@atlaskit/icon-lab/core/ask";
import LabAssetsDataManagerIcon from "@atlaskit/icon-lab/core/assets-data-manager";
import LabAssetsGraphIcon from "@atlaskit/icon-lab/core/assets-graph";
import LabAssetsObjectIcon from "@atlaskit/icon-lab/core/assets-object";
import LabAssetsObjectTypeIcon from "@atlaskit/icon-lab/core/assets-object-type";
import LabAssetsSchemaIcon from "@atlaskit/icon-lab/core/assets-schema";
import LabAtomIcon from "@atlaskit/icon-lab/core/atom";
import LabAudioWaveformIcon from "@atlaskit/icon-lab/core/audio-waveform";
import LabBeachUmbrellaIcon from "@atlaskit/icon-lab/core/beach-umbrella";
import LabBlastRadiusIcon from "@atlaskit/icon-lab/core/blast-radius";
import LabBlockSyncedIcon from "@atlaskit/icon-lab/core/block-synced";
import LabBluetoothIcon from "@atlaskit/icon-lab/core/bluetooth";
import LabBlurIcon from "@atlaskit/icon-lab/core/blur";
import LabBookOpenIcon from "@atlaskit/icon-lab/core/book-open";
import LabBooleanIcon from "@atlaskit/icon-lab/core/boolean";
import LabBrowserExtensionIcon from "@atlaskit/icon-lab/core/browser-extension";
import LabCalculateIcon from "@atlaskit/icon-lab/core/calculate";
import LabCapabilityIcon from "@atlaskit/icon-lab/core/capability";
import LabCartIcon from "@atlaskit/icon-lab/core/cart";
import LabChartAreaIcon from "@atlaskit/icon-lab/core/chart-area";
import LabChartBarLineIcon from "@atlaskit/icon-lab/core/chart-bar-line";
import LabChartBoxPlotIcon from "@atlaskit/icon-lab/core/chart-box-plot";
import LabChartBulletIcon from "@atlaskit/icon-lab/core/chart-bullet";
import LabChartExtrapolateIcon from "@atlaskit/icon-lab/core/chart-extrapolate";
import LabChartFunnelIcon from "@atlaskit/icon-lab/core/chart-funnel";
import LabChartScatterPlotIcon from "@atlaskit/icon-lab/core/chart-scatter-plot";
import LabCloudIcon from "@atlaskit/icon-lab/core/cloud";
import LabCloudOfflineIcon from "@atlaskit/icon-lab/core/cloud-offline";
import LabCloudSavedIcon from "@atlaskit/icon-lab/core/cloud-saved";
import LabCoinsIcon from "@atlaskit/icon-lab/core/coins";
import LabColourNoneIcon from "@atlaskit/icon-lab/core/colour-none";
import LabCompareIcon from "@atlaskit/icon-lab/core/compare";
import LabCompassHingedIcon from "@atlaskit/icon-lab/core/compass-hinged";
import LabContinueWhenIcon from "@atlaskit/icon-lab/core/continue-when";
import LabCrossOctagonIcon from "@atlaskit/icon-lab/core/cross-octagon";
import LabCursorIcon from "@atlaskit/icon-lab/core/cursor";
import LabCursorStrikethroughIcon from "@atlaskit/icon-lab/core/cursor-strikethrough";
import LabDashDoubleIcon from "@atlaskit/icon-lab/core/dash-double";
import LabDataAppIcon from "@atlaskit/icon-lab/core/data-app";
import LabDataBucketIcon from "@atlaskit/icon-lab/core/data-bucket";
import LabDataFormulaIcon from "@atlaskit/icon-lab/core/data-formula";
import LabDataFunctionIcon from "@atlaskit/icon-lab/core/data-function";
import LabDataPivotIcon from "@atlaskit/icon-lab/core/data-pivot";
import LabDataTransposeIcon from "@atlaskit/icon-lab/core/data-transpose";
import LabDataUnpivotIcon from "@atlaskit/icon-lab/core/data-unpivot";
import LabDataVisualizationHeatmapIcon from "@atlaskit/icon-lab/core/data-visualization-heatmap";
import LabDataVisualizationMetricIcon from "@atlaskit/icon-lab/core/data-visualization-metric";
import LabDataZeroFillIcon from "@atlaskit/icon-lab/core/data-zero-fill";
import LabDatabaseStorageIcon from "@atlaskit/icon-lab/core/database-storage";
import LabDatabaseStorageCacheIcon from "@atlaskit/icon-lab/core/database-storage-cache";
import LabDirectoryIcon from "@atlaskit/icon-lab/core/directory";
import LabDistributeSpacingHorizontalIcon from "@atlaskit/icon-lab/core/distribute-spacing-horizontal";
import LabDistributeSpacingVerticalIcon from "@atlaskit/icon-lab/core/distribute-spacing-vertical";
import LabDividerElementIcon from "@atlaskit/icon-lab/core/divider-element";
import LabDockToolbarTopIcon from "@atlaskit/icon-lab/core/dock-toolbar-top";
import LabDrawIcon from "@atlaskit/icon-lab/core/draw";
import LabDropShadowIcon from "@atlaskit/icon-lab/core/drop-shadow";
import LabDuplicateIcon from "@atlaskit/icon-lab/core/duplicate";
import LabEditionsIcon from "@atlaskit/icon-lab/core/editions";
import LabExpandElementIcon from "@atlaskit/icon-lab/core/expand-element";
import LabEyedropperIcon from "@atlaskit/icon-lab/core/eyedropper";
import LabFieldSelectIcon from "@atlaskit/icon-lab/core/field-select";
import LabFieldTextIcon from "@atlaskit/icon-lab/core/field-text";
import LabFlowerIcon from "@atlaskit/icon-lab/core/flower";
import LabFolderSharedIcon from "@atlaskit/icon-lab/core/folder-shared";
import LabGenerativeDateIcon from "@atlaskit/icon-lab/core/generative-date";
import LabGenerativeIndicatorIcon from "@atlaskit/icon-lab/core/generative-indicator";
import LabGiftIcon from "@atlaskit/icon-lab/core/gift";
import LabGlobeStrikethroughIcon from "@atlaskit/icon-lab/core/globe-strikethrough";
import LabGroupIcon from "@atlaskit/icon-lab/core/group";
import LabGroupSelectionIcon from "@atlaskit/icon-lab/core/group-selection";
import LabGroupUngroupSelectionIcon from "@atlaskit/icon-lab/core/group-ungroup-selection";
import LabHandClosedIcon from "@atlaskit/icon-lab/core/hand-closed";
import LabHandOpenIcon from "@atlaskit/icon-lab/core/hand-open";
import LabHandRaisedIcon from "@atlaskit/icon-lab/core/hand-raised";
import LabHistoryIcon from "@atlaskit/icon-lab/core/history";
import LabHourglassIcon from "@atlaskit/icon-lab/core/hourglass";
import LabIfElseIcon from "@atlaskit/icon-lab/core/if-else";
import LabImageAltTextIcon from "@atlaskit/icon-lab/core/image-alt-text";
import LabImageCropIcon from "@atlaskit/icon-lab/core/image-crop";
import LabImageStrikethroughIcon from "@atlaskit/icon-lab/core/image-strikethrough";
import LabIncognitoIcon from "@atlaskit/icon-lab/core/incognito";
import LabInitiativeIcon from "@atlaskit/icon-lab/core/initiative";
import LabJiraIcon from "@atlaskit/icon-lab/core/jira";
import LabJiraAddIcon from "@atlaskit/icon-lab/core/jira-add";
import LabJiraUploadIcon from "@atlaskit/icon-lab/core/jira-upload";
import LabJourneysIcon from "@atlaskit/icon-lab/core/journeys";
import LabKanbanIcon from "@atlaskit/icon-lab/core/kanban";
import LabKeyIcon from "@atlaskit/icon-lab/core/key";
import LabLayoutFiveColumnsIcon from "@atlaskit/icon-lab/core/layout-five-columns";
import LabLayoutFourColumnsIcon from "@atlaskit/icon-lab/core/layout-four-columns";
import LabLayoutThreeColumnsSidebarsLeftIcon from "@atlaskit/icon-lab/core/layout-three-columns-sidebars-left";
import LabLayoutThreeColumnsSidebarsRightIcon from "@atlaskit/icon-lab/core/layout-three-columns-sidebars-right";
import LabLinkRestrictedAccessIcon from "@atlaskit/icon-lab/core/link-restricted-access";
import LabLozengeIcon from "@atlaskit/icon-lab/core/lozenge";
import LabMergeQueueIcon from "@atlaskit/icon-lab/core/merge-queue";
import LabMicrophoneStrikethroughIcon from "@atlaskit/icon-lab/core/microphone-strikethrough";
import LabMilestoneCompleteIcon from "@atlaskit/icon-lab/core/milestone-complete";
import LabMilestoneIncompleteIcon from "@atlaskit/icon-lab/core/milestone-incomplete";
import LabMilestoneMultipleIcon from "@atlaskit/icon-lab/core/milestone-multiple";
import LabMilestoneOverdueIcon from "@atlaskit/icon-lab/core/milestone-overdue";
import LabMissedCallIcon from "@atlaskit/icon-lab/core/missed-call";
import LabNotepadIcon from "@atlaskit/icon-lab/core/notepad";
import LabPageLiveDocIcon from "@atlaskit/icon-lab/core/page-live-doc";
import LabPaintBrushIcon from "@atlaskit/icon-lab/core/paint-brush";
import LabPaintRollerIcon from "@atlaskit/icon-lab/core/paint-roller";
import LabPanelIcon from "@atlaskit/icon-lab/core/panel";
import LabPartyPopperIcon from "@atlaskit/icon-lab/core/party-popper";
import LabPencilIcon from "@atlaskit/icon-lab/core/pencil";
import LabPersonVoiceoverIcon from "@atlaskit/icon-lab/core/person-voiceover";
import LabPinStrikethroughIcon from "@atlaskit/icon-lab/core/pin-strikethrough";
import LabPipelineIcon from "@atlaskit/icon-lab/core/pipeline";
import LabPlanIcon from "@atlaskit/icon-lab/core/plan";
import LabPlaylistIcon from "@atlaskit/icon-lab/core/playlist";
import LabPlaylistAddIcon from "@atlaskit/icon-lab/core/playlist-add";
import LabPlaylistAddedIcon from "@atlaskit/icon-lab/core/playlist-added";
import LabPlaylistRemoveIcon from "@atlaskit/icon-lab/core/playlist-remove";
import LabPlusCircleIcon from "@atlaskit/icon-lab/core/plus-circle";
import LabPowerIcon from "@atlaskit/icon-lab/core/power";
import LabPowerCableIcon from "@atlaskit/icon-lab/core/power-cable";
import LabQrCodeIcon from "@atlaskit/icon-lab/core/qr-code";
import LabQueuePopInIcon from "@atlaskit/icon-lab/core/queue-pop-in";
import LabQueuePopOutIcon from "@atlaskit/icon-lab/core/queue-pop-out";
import LabRandomizeIcon from "@atlaskit/icon-lab/core/randomize";
import LabRepeatIcon from "@atlaskit/icon-lab/core/repeat";
import LabReplyLeftIcon from "@atlaskit/icon-lab/core/reply-left";
import LabReplyRightIcon from "@atlaskit/icon-lab/core/reply-right";
import LabReturnIcon from "@atlaskit/icon-lab/core/return";
import LabRoadmapsPlanIcon from "@atlaskit/icon-lab/core/roadmaps-plan";
import LabRoadmapsServiceIcon from "@atlaskit/icon-lab/core/roadmaps-service";
import LabRovoIcon from "@atlaskit/icon-lab/core/rovo";
import LabRssFeedIcon from "@atlaskit/icon-lab/core/rss-feed";
import LabSaveIcon from "@atlaskit/icon-lab/core/save";
import LabScreenRecordIcon from "@atlaskit/icon-lab/core/screen-record";
import LabSectionIcon from "@atlaskit/icon-lab/core/section";
import LabServiceIcon from "@atlaskit/icon-lab/core/service";
import LabSignatureIcon from "@atlaskit/icon-lab/core/signature";
import LabSignpostIcon from "@atlaskit/icon-lab/core/signpost";
import LabSkillIcon from "@atlaskit/icon-lab/core/skill";
import LabSkipIcon from "@atlaskit/icon-lab/core/skip";
import LabSkipUnskipIcon from "@atlaskit/icon-lab/core/skip-unskip";
import LabSortOptionsIcon from "@atlaskit/icon-lab/core/sort-options";
import LabSpacesIcon from "@atlaskit/icon-lab/core/spaces";
import LabSpeedometerLeftIcon from "@atlaskit/icon-lab/core/speedometer-left";
import LabSpeedometerRightIcon from "@atlaskit/icon-lab/core/speedometer-right";
import LabSpeedometerUpIcon from "@atlaskit/icon-lab/core/speedometer-up";
import LabSplitParallelIcon from "@atlaskit/icon-lab/core/split-parallel";
import LabStampIcon from "@atlaskit/icon-lab/core/stamp";
import LabStatusWorkflowCancelledIcon from "@atlaskit/icon-lab/core/status-workflow-cancelled";
import LabStatusWorkflowDangerIcon from "@atlaskit/icon-lab/core/status-workflow-danger";
import LabStatusWorkflowInProgressIcon from "@atlaskit/icon-lab/core/status-workflow-in-progress";
import LabStatusWorkflowInReviewIcon from "@atlaskit/icon-lab/core/status-workflow-in-review";
import LabStatusWorkflowInactiveIcon from "@atlaskit/icon-lab/core/status-workflow-inactive";
import LabStatusWorkflowIncompleteIcon from "@atlaskit/icon-lab/core/status-workflow-incomplete";
import LabStatusWorkflowPausedIcon from "@atlaskit/icon-lab/core/status-workflow-paused";
import LabStatusWorkflowReturnedIcon from "@atlaskit/icon-lab/core/status-workflow-returned";
import LabStatusWorkflowScheduledIcon from "@atlaskit/icon-lab/core/status-workflow-scheduled";
import LabStatusWorkflowStoppedIcon from "@atlaskit/icon-lab/core/status-workflow-stopped";
import LabStatusWorkflowSuccessIcon from "@atlaskit/icon-lab/core/status-workflow-success";
import LabStatusWorkflowWarningIcon from "@atlaskit/icon-lab/core/status-workflow-warning";
import LabStickerIcon from "@atlaskit/icon-lab/core/sticker";
import LabStudioIcon from "@atlaskit/icon-lab/core/studio";
import LabSuggestedEditIcon from "@atlaskit/icon-lab/core/suggested-edit";
import LabSunsetIcon from "@atlaskit/icon-lab/core/sunset";
import LabSurveyIcon from "@atlaskit/icon-lab/core/survey";
import LabSwapIcon from "@atlaskit/icon-lab/core/swap";
import LabSwitchCaseIcon from "@atlaskit/icon-lab/core/switch-case";
import LabSyncIcon from "@atlaskit/icon-lab/core/sync";
import LabTabIcon from "@atlaskit/icon-lab/core/tab";
import LabTableRowLimitIcon from "@atlaskit/icon-lab/core/table-row-limit";
import LabTakeoutContainerIcon from "@atlaskit/icon-lab/core/takeout-container";
import LabTalentIcon from "@atlaskit/icon-lab/core/talent";
import LabTeamworkGraphIcon from "@atlaskit/icon-lab/core/teamwork-graph";
import LabTelescopeIcon from "@atlaskit/icon-lab/core/telescope";
import LabTemplateIcon from "@atlaskit/icon-lab/core/template";
import LabTemplateSyncIcon from "@atlaskit/icon-lab/core/template-sync";
import LabTerminalIcon from "@atlaskit/icon-lab/core/terminal";
import LabTextAdjustLengthIcon from "@atlaskit/icon-lab/core/text-adjust-length";
import LabTextAudioTranscriptIcon from "@atlaskit/icon-lab/core/text-audio-transcript";
import LabTextBoldItalicIcon from "@atlaskit/icon-lab/core/text-bold-italic";
import LabTextBoldItalicStrikethroughIcon from "@atlaskit/icon-lab/core/text-bold-italic-strikethrough";
import LabTextBoldItalicUnderlineIcon from "@atlaskit/icon-lab/core/text-bold-italic-underline";
import LabTextBoldItalicUnderlineStrikethroughIcon from "@atlaskit/icon-lab/core/text-bold-italic-underline-strikethrough";
import LabTextBoldStrikethroughIcon from "@atlaskit/icon-lab/core/text-bold-strikethrough";
import LabTextBoldUnderlineIcon from "@atlaskit/icon-lab/core/text-bold-underline";
import LabTextBoldUnderlineStrikethroughIcon from "@atlaskit/icon-lab/core/text-bold-underline-strikethrough";
import LabTextConclusionAddIcon from "@atlaskit/icon-lab/core/text-conclusion-add";
import LabTextCursorIcon from "@atlaskit/icon-lab/core/text-cursor";
import LabTextDensityCompressIcon from "@atlaskit/icon-lab/core/text-density-compress";
import LabTextDensityExpandIcon from "@atlaskit/icon-lab/core/text-density-expand";
import LabTextHeadingFiveIcon from "@atlaskit/icon-lab/core/text-heading-five";
import LabTextHeadingFourIcon from "@atlaskit/icon-lab/core/text-heading-four";
import LabTextHeadingOneIcon from "@atlaskit/icon-lab/core/text-heading-one";
import LabTextHeadingSixIcon from "@atlaskit/icon-lab/core/text-heading-six";
import LabTextHeadingThreeIcon from "@atlaskit/icon-lab/core/text-heading-three";
import LabTextHeadingTwoIcon from "@atlaskit/icon-lab/core/text-heading-two";
import LabTextIntroductionAddIcon from "@atlaskit/icon-lab/core/text-introduction-add";
import LabTextItalicStrikethroughIcon from "@atlaskit/icon-lab/core/text-italic-strikethrough";
import LabTextItalicUnderlineIcon from "@atlaskit/icon-lab/core/text-italic-underline";
import LabTextItalicUnderlineStrikethroughIcon from "@atlaskit/icon-lab/core/text-italic-underline-strikethrough";
import LabTextLengthenIcon from "@atlaskit/icon-lab/core/text-lengthen";
import LabTextLetterCaseIcon from "@atlaskit/icon-lab/core/text-letter-case";
import LabTextParagraphIcon from "@atlaskit/icon-lab/core/text-paragraph";
import LabTextRephraseIcon from "@atlaskit/icon-lab/core/text-rephrase";
import LabTextSubscriptIcon from "@atlaskit/icon-lab/core/text-subscript";
import LabTextSuperscriptIcon from "@atlaskit/icon-lab/core/text-superscript";
import LabTextUnderlineStrikethroughIcon from "@atlaskit/icon-lab/core/text-underline-strikethrough";
import LabTicketIcon from "@atlaskit/icon-lab/core/ticket";
import LabTidyIcon from "@atlaskit/icon-lab/core/tidy";
import LabVariableIcon from "@atlaskit/icon-lab/core/variable";
import LabVehicleAirplaneIcon from "@atlaskit/icon-lab/core/vehicle-airplane";
import LabVehicleTrainIcon from "@atlaskit/icon-lab/core/vehicle-train";
import LabVideoCaptionsStylizedIcon from "@atlaskit/icon-lab/core/video-captions-stylized";
import LabVideoClipIcon from "@atlaskit/icon-lab/core/video-clip";
import LabVideoClosedCaptionsIcon from "@atlaskit/icon-lab/core/video-closed-captions";
import LabVideoClosedCaptionsFilledIcon from "@atlaskit/icon-lab/core/video-closed-captions-filled";
import LabVideoFastForwardIcon from "@atlaskit/icon-lab/core/video-fast-forward";
import LabVideoFastForwardOverlayIcon from "@atlaskit/icon-lab/core/video-fast-forward-overlay";
import LabVideoHdIcon from "@atlaskit/icon-lab/core/video-hd";
import LabVideoHdFilledIcon from "@atlaskit/icon-lab/core/video-hd-filled";
import LabVideoMiniplayerIcon from "@atlaskit/icon-lab/core/video-miniplayer";
import LabVideoOverlayToolsIcon from "@atlaskit/icon-lab/core/video-overlay-tools";
import LabVideoPlayCircleIcon from "@atlaskit/icon-lab/core/video-play-circle";
import LabVideoRecordIcon from "@atlaskit/icon-lab/core/video-record";
import LabVideoRewindIcon from "@atlaskit/icon-lab/core/video-rewind";
import LabVideoRewindOverlayIcon from "@atlaskit/icon-lab/core/video-rewind-overlay";
import LabVideoSkipBackwardFiveIcon from "@atlaskit/icon-lab/core/video-skip-backward-five";
import LabVideoSkipForwardFiveIcon from "@atlaskit/icon-lab/core/video-skip-forward-five";
import LabVideoStrikethroughIcon from "@atlaskit/icon-lab/core/video-strikethrough";
import LabVideoTheaterModeIcon from "@atlaskit/icon-lab/core/video-theater-mode";
import LabVideoTimelineClipSplitIcon from "@atlaskit/icon-lab/core/video-timeline-clip-split";
import LabVideoTimelineEditorIcon from "@atlaskit/icon-lab/core/video-timeline-editor";
import LabVideoWatchLaterRemoveIcon from "@atlaskit/icon-lab/core/video-watch-later-remove";
import LabVideoWatchLaterSavedIcon from "@atlaskit/icon-lab/core/video-watch-later-saved";
import LabViewTypeBoardHomeIcon from "@atlaskit/icon-lab/core/view-type-board-home";
import LabViewTypeCardHomeIcon from "@atlaskit/icon-lab/core/view-type-card-home";
import LabViewTypeTableHomeIcon from "@atlaskit/icon-lab/core/view-type-table-home";
import LabViewsIcon from "@atlaskit/icon-lab/core/views";
import LabVulnerabilityIcon from "@atlaskit/icon-lab/core/vulnerability";
import LabWalletIcon from "@atlaskit/icon-lab/core/wallet";
import LabWarningOutlineIcon from "@atlaskit/icon-lab/core/warning-outline";
import LabWebhookIcon from "@atlaskit/icon-lab/core/webhook";
import LabWelcomeFeedIcon from "@atlaskit/icon-lab/core/welcome-feed";
import LabWorkItemAddIcon from "@atlaskit/icon-lab/core/work-item-add";
import LabWorkflowControlsIcon from "@atlaskit/icon-lab/core/workflow-controls";
import LabWorldIcon from "@atlaskit/icon-lab/core/world";
import LabWrenchIcon from "@atlaskit/icon-lab/core/wrench";

type IconComponent = (props: NewCoreIconProps) => JSX.Element;

export const ICON_REGISTRY: ReadonlyMap<string, IconComponent> = new Map([
	["accessibility", AccessibilityIcon],
	["add", AddIcon],
	["ai-agent", AiAgentIcon],
	["ai-chat", AiChatIcon],
	["ai-generative-text-summary", AiGenerativeTextSummaryIcon],
	["ai-sparkle", AiSparkleIcon],
	["alert", AlertIcon],
	["align-image-center", AlignImageCenterIcon],
	["align-image-left", AlignImageLeftIcon],
	["align-image-right", AlignImageRightIcon],
	["align-text-center", AlignTextCenterIcon],
	["align-text-left", AlignTextLeftIcon],
	["align-text-right", AlignTextRightIcon],
	["angle-brackets", AngleBracketsIcon],
	["api", ApiIcon],
	["app", AppIcon],
	["app-switcher", AppSwitcherIcon],
	["app-switcher-legacy", AppSwitcherLegacyIcon],
	["apps", AppsIcon],
	["archive-box", ArchiveBoxIcon],
	["arrow-down", ArrowDownIcon],
	["arrow-down-left", ArrowDownLeftIcon],
	["arrow-down-right", ArrowDownRightIcon],
	["arrow-left", ArrowLeftIcon],
	["arrow-right", ArrowRightIcon],
	["arrow-up", ArrowUpIcon],
	["arrow-up-left", ArrowUpLeftIcon],
	["arrow-up-right", ArrowUpRightIcon],
	["assets", AssetsIcon],
	["atlassian-intelligence", AtlassianIntelligenceIcon],
	["attachment", AttachmentIcon],
	["audio", AudioIcon],
	["automation", AutomationIcon],
	["backlog", BacklogIcon],
	["basketball", BasketballIcon],
	["board", BoardIcon],
	["boards", BoardsIcon],
	["book-with-bookmark", BookWithBookmarkIcon],
	["border", BorderIcon],
	["branch", BranchIcon],
	["briefcase", BriefcaseIcon],
	["bug", BugIcon],
	["calendar", CalendarIcon],
	["calendar-plus", CalendarPlusIcon],
	["camera", CameraIcon],
	["capture", CaptureIcon],
	["card", CardIcon],
	["cash", CashIcon],
	["changes", ChangesIcon],
	["chart-bar", ChartBarIcon],
	["chart-bubble", ChartBubbleIcon],
	["chart-matrix", ChartMatrixIcon],
	["chart-pie", ChartPieIcon],
	["chart-trend", ChartTrendIcon],
	["chart-trend-down", ChartTrendDownIcon],
	["chart-trend-up", ChartTrendUpIcon],
	["chat-widget", ChatWidgetIcon],
	["check-circle", CheckCircleIcon],
	["check-circle-unchecked", CheckCircleUncheckedIcon],
	["check-mark", CheckMarkIcon],
	["checkbox-checked", CheckboxCheckedIcon],
	["checkbox-indeterminate", CheckboxIndeterminateIcon],
	["checkbox-unchecked", CheckboxUncheckedIcon],
	["chevron-double-left", ChevronDoubleLeftIcon],
	["chevron-double-right", ChevronDoubleRightIcon],
	["chevron-down", ChevronDownIcon],
	["chevron-left", ChevronLeftIcon],
	["chevron-right", ChevronRightIcon],
	["chevron-up", ChevronUpIcon],
	["child-work-items", ChildWorkItemsIcon],
	["clipboard", ClipboardIcon],
	["clock", ClockIcon],
	["close", CloseIcon],
	["cloud-arrow-up", CloudArrowUpIcon],
	["collapse-horizontal", CollapseHorizontalIcon],
	["collapse-vertical", CollapseVerticalIcon],
	["comment", CommentIcon],
	["comment-add", CommentAddIcon],
	["commit", CommitIcon],
	["compass", CompassIcon],
	["component", ComponentIcon],
	["content-width-narrow", ContentWidthNarrowIcon],
	["content-width-wide", ContentWidthWideIcon],
	["content-wrap-left", ContentWrapLeftIcon],
	["content-wrap-right", ContentWrapRightIcon],
	["copy", CopyIcon],
	["credit-card", CreditCardIcon],
	["cross", CrossIcon],
	["cross-circle", CrossCircleIcon],
	["curly-brackets", CurlyBracketsIcon],
	["customize", CustomizeIcon],
	["dashboard", DashboardIcon],
	["data-flow", DataFlowIcon],
	["data-number", DataNumberIcon],
	["data-string", DataStringIcon],
	["database", DatabaseIcon],
	["decision", DecisionIcon],
	["defect", DefectIcon],
	["delete", DeleteIcon],
	["department", DepartmentIcon],
	["device-mobile", DeviceMobileIcon],
	["devices", DevicesIcon],
	["discovery", DiscoveryIcon],
	["download", DownloadIcon],
	["drag-handle-horizontal", DragHandleHorizontalIcon],
	["drag-handle-vertical", DragHandleVerticalIcon],
	["edit", EditIcon],
	["edit-bulk", EditBulkIcon],
	["email", EmailIcon],
	["emoji", EmojiIcon],
	["emoji-add", EmojiAddIcon],
	["emoji-casual", EmojiCasualIcon],
	["emoji-neutral", EmojiNeutralIcon],
	["emoji-remove", EmojiRemoveIcon],
	["epic", EpicIcon],
	["error", ErrorIcon],
	["exclamation-square", ExclamationSquareIcon],
	["expand-horizontal", ExpandHorizontalIcon],
	["expand-vertical", ExpandVerticalIcon],
	["eye-open", EyeOpenIcon],
	["eye-open-filled", EyeOpenFilledIcon],
	["eye-open-strikethrough", EyeOpenStrikethroughIcon],
	["feed", FeedIcon],
	["feedback", FeedbackIcon],
	["field", FieldIcon],
	["field-alert", FieldAlertIcon],
	["field-checkbox-group", FieldCheckboxGroupIcon],
	["field-dropdown", FieldDropdownIcon],
	["field-radio-group", FieldRadioGroupIcon],
	["file", FileIcon],
	["files", FilesIcon],
	["filter", FilterIcon],
	["flag", FlagIcon],
	["flag-filled", FlagFilledIcon],
	["flask", FlaskIcon],
	["focus-area", FocusAreaIcon],
	["folder-closed", FolderClosedIcon],
	["folder-open", FolderOpenIcon],
	["form", FormIcon],
	["fullscreen-enter", FullscreenEnterIcon],
	["fullscreen-exit", FullscreenExitIcon],
	["glasses", GlassesIcon],
	["globe", GlobeIcon],
	["goal", GoalIcon],
	["grid", GridIcon],
	["grow-diagonal", GrowDiagonalIcon],
	["grow-horizontal", GrowHorizontalIcon],
	["grow-vertical", GrowVerticalIcon],
	["hashtag", HashtagIcon],
	["headphones", HeadphonesIcon],
	["heart", HeartIcon],
	["highlight", HighlightIcon],
	["home", HomeIcon],
	["image", ImageIcon],
	["image-fullscreen", ImageFullscreenIcon],
	["image-inline", ImageInlineIcon],
	["image-scaled", ImageScaledIcon],
	["inbox", InboxIcon],
	["incident", IncidentIcon],
	["information", InformationIcon],
	["information-circle", InformationCircleIcon],
	["key-result", KeyResultIcon],
	["layout-one-column", LayoutOneColumnIcon],
	["layout-three-columns", LayoutThreeColumnsIcon],
	["layout-three-columns-sidebars", LayoutThreeColumnsSidebarsIcon],
	["layout-two-columns", LayoutTwoColumnsIcon],
	["layout-two-columns-sidebar-left", LayoutTwoColumnsSidebarLeftIcon],
	["layout-two-columns-sidebar-right", LayoutTwoColumnsSidebarRightIcon],
	["library", LibraryIcon],
	["lightbulb", LightbulbIcon],
	["link", LinkIcon],
	["link-broken", LinkBrokenIcon],
	["link-external", LinkExternalIcon],
	["list-bulleted", ListBulletedIcon],
	["list-checklist", ListChecklistIcon],
	["list-numbered", ListNumberedIcon],
	["lobby-bell", LobbyBellIcon],
	["location", LocationIcon],
	["lock-locked", LockLockedIcon],
	["lock-unlocked", LockUnlockedIcon],
	["log-in", LogInIcon],
	["log-out", LogOutIcon],
	["magic-wand", MagicWandIcon],
	["markdown", MarkdownIcon],
	["marketplace", MarketplaceIcon],
	["maximize", MaximizeIcon],
	["megaphone", MegaphoneIcon],
	["mention", MentionIcon],
	["menu", MenuIcon],
	["merge-failure", MergeFailureIcon],
	["merge-success", MergeSuccessIcon],
	["microphone", MicrophoneIcon],
	["minimize", MinimizeIcon],
	["minus", MinusIcon],
	["minus-square", MinusSquareIcon],
	["node", NodeIcon],
	["note", NoteIcon],
	["notification", NotificationIcon],
	["notification-muted", NotificationMutedIcon],
	["objective", ObjectiveIcon],
	["office-building", OfficeBuildingIcon],
	["on-call", OnCallIcon],
	["operations", OperationsIcon],
	["page", PageIcon],
	["pages", PagesIcon],
	["paint-bucket", PaintBucketIcon],
	["paint-palette", PaintPaletteIcon],
	["panel-left", PanelLeftIcon],
	["panel-right", PanelRightIcon],
	["pen", PenIcon],
	["people-group", PeopleGroupIcon],
	["person", PersonIcon],
	["person-add", PersonAddIcon],
	["person-added", PersonAddedIcon],
	["person-avatar", PersonAvatarIcon],
	["person-offboard", PersonOffboardIcon],
	["person-remove", PersonRemoveIcon],
	["person-warning", PersonWarningIcon],
	["phone", PhoneIcon],
	["pin", PinIcon],
	["pin-filled", PinFilledIcon],
	["plus-square", PlusSquareIcon],
	["power-plug", PowerPlugIcon],
	["premium", PremiumIcon],
	["presenter-mode", PresenterModeIcon],
	["printer", PrinterIcon],
	["priority-blocker", PriorityBlockerIcon],
	["priority-critical", PriorityCriticalIcon],
	["priority-high", PriorityHighIcon],
	["priority-highest", PriorityHighestIcon],
	["priority-low", PriorityLowIcon],
	["priority-lowest", PriorityLowestIcon],
	["priority-major", PriorityMajorIcon],
	["priority-medium", PriorityMediumIcon],
	["priority-minor", PriorityMinorIcon],
	["priority-trivial", PriorityTrivialIcon],
	["problem", ProblemIcon],
	["project", ProjectIcon],
	["project-status", ProjectStatusIcon],
	["projection-screen", ProjectionScreenIcon],
	["pull-request", PullRequestIcon],
	["pulse", PulseIcon],
	["question-circle", QuestionCircleIcon],
	["quotation-mark", QuotationMarkIcon],
	["radio-checked", RadioCheckedIcon],
	["radio-unchecked", RadioUncheckedIcon],
	["redo", RedoIcon],
	["refresh", RefreshIcon],
	["release", ReleaseIcon],
	["retry", RetryIcon],
	["roadmap", RoadmapIcon],
	["rovo-chat", RovoChatIcon],
	["scales", ScalesIcon],
	["scorecard", ScorecardIcon],
	["screen", ScreenIcon],
	["screen-plus", ScreenPlusIcon],
	["search", SearchIcon],
	["send", SendIcon],
	["settings", SettingsIcon],
	["shapes", ShapesIcon],
	["share", ShareIcon],
	["shield", ShieldIcon],
	["shield-strikethrough", ShieldStrikethroughIcon],
	["shortcut", ShortcutIcon],
	["show-more-horizontal", ShowMoreHorizontalIcon],
	["show-more-vertical", ShowMoreVerticalIcon],
	["shrink-diagonal", ShrinkDiagonalIcon],
	["shrink-horizontal", ShrinkHorizontalIcon],
	["shrink-vertical", ShrinkVerticalIcon],
	["sidebar-collapse", SidebarCollapseIcon],
	["sidebar-expand", SidebarExpandIcon],
	["smart-link", SmartLinkIcon],
	["smart-link-card", SmartLinkCardIcon],
	["smart-link-embed", SmartLinkEmbedIcon],
	["smart-link-inline", SmartLinkInlineIcon],
	["smart-link-list", SmartLinkListIcon],
	["snippet", SnippetIcon],
	["sort-ascending", SortAscendingIcon],
	["sort-descending", SortDescendingIcon],
	["spreadsheet", SpreadsheetIcon],
	["sprint", SprintIcon],
	["star-starred", StarStarredIcon],
	["star-unstarred", StarUnstarredIcon],
	["status-discovery", StatusDiscoveryIcon],
	["status-error", StatusErrorIcon],
	["status-information", StatusInformationIcon],
	["status-success", StatusSuccessIcon],
	["status-verified", StatusVerifiedIcon],
	["status-warning", StatusWarningIcon],
	["stopwatch", StopwatchIcon],
	["story", StoryIcon],
	["stroke-weight-extra-large", StrokeWeightExtraLargeIcon],
	["stroke-weight-large", StrokeWeightLargeIcon],
	["stroke-weight-medium", StrokeWeightMediumIcon],
	["stroke-weight-small", StrokeWeightSmallIcon],
	["subtasks", SubtasksIcon],
	["success", SuccessIcon],
	["support", SupportIcon],
	["table", TableIcon],
	["table-cell-clear", TableCellClearIcon],
	["table-cell-merge", TableCellMergeIcon],
	["table-cell-split", TableCellSplitIcon],
	["table-column-add-left", TableColumnAddLeftIcon],
	["table-column-add-right", TableColumnAddRightIcon],
	["table-column-delete", TableColumnDeleteIcon],
	["table-column-move-left", TableColumnMoveLeftIcon],
	["table-column-move-right", TableColumnMoveRightIcon],
	["table-columns-distribute", TableColumnsDistributeIcon],
	["table-row-add-above", TableRowAddAboveIcon],
	["table-row-add-below", TableRowAddBelowIcon],
	["table-row-delete", TableRowDeleteIcon],
	["table-row-move-down", TableRowMoveDownIcon],
	["table-row-move-up", TableRowMoveUpIcon],
	["tag", TagIcon],
	["takeout-food", TakeoutFoodIcon],
	["target", TargetIcon],
	["task", TaskIcon],
	["task-in-progress", TaskInProgressIcon],
	["task-to-do", TaskToDoIcon],
	["tasks", TasksIcon],
	["teams", TeamsIcon],
	["text", TextIcon],
	["text-bold", TextBoldIcon],
	["text-heading", TextHeadingIcon],
	["text-indent-left", TextIndentLeftIcon],
	["text-indent-right", TextIndentRightIcon],
	["text-italic", TextItalicIcon],
	["text-shorten", TextShortenIcon],
	["text-spellcheck", TextSpellcheckIcon],
	["text-strikethrough", TextStrikethroughIcon],
	["text-style", TextStyleIcon],
	["text-underline", TextUnderlineIcon],
	["text-wrap", TextWrapIcon],
	["theme", ThemeIcon],
	["thumbs-down", ThumbsDownIcon],
	["thumbs-up", ThumbsUpIcon],
	["timeline", TimelineIcon],
	["tools", ToolsIcon],
	["transition", TransitionIcon],
	["translate", TranslateIcon],
	["tree", TreeIcon],
	["undo", UndoIcon],
	["upload", UploadIcon],
	["vehicle-car", VehicleCarIcon],
	["video", VideoIcon],
	["video-next", VideoNextIcon],
	["video-next-overlay", VideoNextOverlayIcon],
	["video-pause", VideoPauseIcon],
	["video-pause-overlay", VideoPauseOverlayIcon],
	["video-play", VideoPlayIcon],
	["video-play-overlay", VideoPlayOverlayIcon],
	["video-previous", VideoPreviousIcon],
	["video-previous-overlay", VideoPreviousOverlayIcon],
	["video-skip-backward-fifteen", VideoSkipBackwardFifteenIcon],
	["video-skip-backward-ten", VideoSkipBackwardTenIcon],
	["video-skip-forward-fifteen", VideoSkipForwardFifteenIcon],
	["video-skip-forward-ten", VideoSkipForwardTenIcon],
	["video-stop", VideoStopIcon],
	["video-stop-overlay", VideoStopOverlayIcon],
	["volume-high", VolumeHighIcon],
	["volume-low", VolumeLowIcon],
	["volume-muted", VolumeMutedIcon],
	["warning", WarningIcon],
	["whiteboard", WhiteboardIcon],
	["work-item", WorkItemIcon],
	["work-items", WorkItemsIcon],
	["zoom-in", ZoomInIcon],
	["zoom-out", ZoomOutIcon],
	["lab/ai-bot", LabAiBotIcon],
	["lab/ai-compute", LabAiComputeIcon],
	["lab/ai-generative-audio-briefing", LabAiGenerativeAudioBriefingIcon],
	["lab/ai-generative-chapters", LabAiGenerativeChaptersIcon],
	["lab/ai-generative-cleanup", LabAiGenerativeCleanupIcon],
	["lab/ai-generative-remove", LabAiGenerativeRemoveIcon],
	["lab/ai-generative-remove-silence", LabAiGenerativeRemoveSilenceIcon],
	["lab/ai-generative-text", LabAiGenerativeTextIcon],
	["lab/ai-generative-text-title", LabAiGenerativeTextTitleIcon],
	["lab/ai-model", LabAiModelIcon],
	["lab/ai-search", LabAiSearchIcon],
	["lab/arrow-curved-down-left", LabArrowCurvedDownLeftIcon],
	["lab/arrow-curved-down-right", LabArrowCurvedDownRightIcon],
	["lab/arrow-curved-left-down", LabArrowCurvedLeftDownIcon],
	["lab/arrow-curved-left-up", LabArrowCurvedLeftUpIcon],
	["lab/arrow-curved-right-down", LabArrowCurvedRightDownIcon],
	["lab/arrow-curved-right-up", LabArrowCurvedRightUpIcon],
	["lab/arrow-curved-up-left", LabArrowCurvedUpLeftIcon],
	["lab/arrow-curved-up-right", LabArrowCurvedUpRightIcon],
	["lab/arrow-end", LabArrowEndIcon],
	["lab/arrow-start", LabArrowStartIcon],
	["lab/arrows-diagonal-up-right-down-left", LabArrowsDiagonalUpRightDownLeftIcon],
	["lab/ask", LabAskIcon],
	["lab/assets-data-manager", LabAssetsDataManagerIcon],
	["lab/assets-graph", LabAssetsGraphIcon],
	["lab/assets-object", LabAssetsObjectIcon],
	["lab/assets-object-type", LabAssetsObjectTypeIcon],
	["lab/assets-schema", LabAssetsSchemaIcon],
	["lab/atom", LabAtomIcon],
	["lab/audio-waveform", LabAudioWaveformIcon],
	["lab/beach-umbrella", LabBeachUmbrellaIcon],
	["lab/blast-radius", LabBlastRadiusIcon],
	["lab/block-synced", LabBlockSyncedIcon],
	["lab/bluetooth", LabBluetoothIcon],
	["lab/blur", LabBlurIcon],
	["lab/book-open", LabBookOpenIcon],
	["lab/boolean", LabBooleanIcon],
	["lab/browser-extension", LabBrowserExtensionIcon],
	["lab/calculate", LabCalculateIcon],
	["lab/capability", LabCapabilityIcon],
	["lab/cart", LabCartIcon],
	["lab/chart-area", LabChartAreaIcon],
	["lab/chart-bar-line", LabChartBarLineIcon],
	["lab/chart-box-plot", LabChartBoxPlotIcon],
	["lab/chart-bullet", LabChartBulletIcon],
	["lab/chart-extrapolate", LabChartExtrapolateIcon],
	["lab/chart-funnel", LabChartFunnelIcon],
	["lab/chart-scatter-plot", LabChartScatterPlotIcon],
	["lab/cloud", LabCloudIcon],
	["lab/cloud-offline", LabCloudOfflineIcon],
	["lab/cloud-saved", LabCloudSavedIcon],
	["lab/coins", LabCoinsIcon],
	["lab/colour-none", LabColourNoneIcon],
	["lab/compare", LabCompareIcon],
	["lab/compass-hinged", LabCompassHingedIcon],
	["lab/continue-when", LabContinueWhenIcon],
	["lab/cross-octagon", LabCrossOctagonIcon],
	["lab/cursor", LabCursorIcon],
	["lab/cursor-strikethrough", LabCursorStrikethroughIcon],
	["lab/dash-double", LabDashDoubleIcon],
	["lab/data-app", LabDataAppIcon],
	["lab/data-bucket", LabDataBucketIcon],
	["lab/data-formula", LabDataFormulaIcon],
	["lab/data-function", LabDataFunctionIcon],
	["lab/data-pivot", LabDataPivotIcon],
	["lab/data-transpose", LabDataTransposeIcon],
	["lab/data-unpivot", LabDataUnpivotIcon],
	["lab/data-visualization-heatmap", LabDataVisualizationHeatmapIcon],
	["lab/data-visualization-metric", LabDataVisualizationMetricIcon],
	["lab/data-zero-fill", LabDataZeroFillIcon],
	["lab/database-storage", LabDatabaseStorageIcon],
	["lab/database-storage-cache", LabDatabaseStorageCacheIcon],
	["lab/directory", LabDirectoryIcon],
	["lab/distribute-spacing-horizontal", LabDistributeSpacingHorizontalIcon],
	["lab/distribute-spacing-vertical", LabDistributeSpacingVerticalIcon],
	["lab/divider-element", LabDividerElementIcon],
	["lab/dock-toolbar-top", LabDockToolbarTopIcon],
	["lab/draw", LabDrawIcon],
	["lab/drop-shadow", LabDropShadowIcon],
	["lab/duplicate", LabDuplicateIcon],
	["lab/editions", LabEditionsIcon],
	["lab/expand-element", LabExpandElementIcon],
	["lab/eyedropper", LabEyedropperIcon],
	["lab/field-select", LabFieldSelectIcon],
	["lab/field-text", LabFieldTextIcon],
	["lab/flower", LabFlowerIcon],
	["lab/folder-shared", LabFolderSharedIcon],
	["lab/generative-date", LabGenerativeDateIcon],
	["lab/generative-indicator", LabGenerativeIndicatorIcon],
	["lab/gift", LabGiftIcon],
	["lab/globe-strikethrough", LabGlobeStrikethroughIcon],
	["lab/group", LabGroupIcon],
	["lab/group-selection", LabGroupSelectionIcon],
	["lab/group-ungroup-selection", LabGroupUngroupSelectionIcon],
	["lab/hand-closed", LabHandClosedIcon],
	["lab/hand-open", LabHandOpenIcon],
	["lab/hand-raised", LabHandRaisedIcon],
	["lab/history", LabHistoryIcon],
	["lab/hourglass", LabHourglassIcon],
	["lab/if-else", LabIfElseIcon],
	["lab/image-alt-text", LabImageAltTextIcon],
	["lab/image-crop", LabImageCropIcon],
	["lab/image-strikethrough", LabImageStrikethroughIcon],
	["lab/incognito", LabIncognitoIcon],
	["lab/initiative", LabInitiativeIcon],
	["lab/jira", LabJiraIcon],
	["lab/jira-add", LabJiraAddIcon],
	["lab/jira-upload", LabJiraUploadIcon],
	["lab/journeys", LabJourneysIcon],
	["lab/kanban", LabKanbanIcon],
	["lab/key", LabKeyIcon],
	["lab/layout-five-columns", LabLayoutFiveColumnsIcon],
	["lab/layout-four-columns", LabLayoutFourColumnsIcon],
	["lab/layout-three-columns-sidebars-left", LabLayoutThreeColumnsSidebarsLeftIcon],
	["lab/layout-three-columns-sidebars-right", LabLayoutThreeColumnsSidebarsRightIcon],
	["lab/link-restricted-access", LabLinkRestrictedAccessIcon],
	["lab/lozenge", LabLozengeIcon],
	["lab/merge-queue", LabMergeQueueIcon],
	["lab/microphone-strikethrough", LabMicrophoneStrikethroughIcon],
	["lab/milestone-complete", LabMilestoneCompleteIcon],
	["lab/milestone-incomplete", LabMilestoneIncompleteIcon],
	["lab/milestone-multiple", LabMilestoneMultipleIcon],
	["lab/milestone-overdue", LabMilestoneOverdueIcon],
	["lab/missed-call", LabMissedCallIcon],
	["lab/notepad", LabNotepadIcon],
	["lab/page-live-doc", LabPageLiveDocIcon],
	["lab/paint-brush", LabPaintBrushIcon],
	["lab/paint-roller", LabPaintRollerIcon],
	["lab/panel", LabPanelIcon],
	["lab/party-popper", LabPartyPopperIcon],
	["lab/pencil", LabPencilIcon],
	["lab/person-voiceover", LabPersonVoiceoverIcon],
	["lab/pin-strikethrough", LabPinStrikethroughIcon],
	["lab/pipeline", LabPipelineIcon],
	["lab/plan", LabPlanIcon],
	["lab/playlist", LabPlaylistIcon],
	["lab/playlist-add", LabPlaylistAddIcon],
	["lab/playlist-added", LabPlaylistAddedIcon],
	["lab/playlist-remove", LabPlaylistRemoveIcon],
	["lab/plus-circle", LabPlusCircleIcon],
	["lab/power", LabPowerIcon],
	["lab/power-cable", LabPowerCableIcon],
	["lab/qr-code", LabQrCodeIcon],
	["lab/queue-pop-in", LabQueuePopInIcon],
	["lab/queue-pop-out", LabQueuePopOutIcon],
	["lab/randomize", LabRandomizeIcon],
	["lab/repeat", LabRepeatIcon],
	["lab/reply-left", LabReplyLeftIcon],
	["lab/reply-right", LabReplyRightIcon],
	["lab/return", LabReturnIcon],
	["lab/roadmaps-plan", LabRoadmapsPlanIcon],
	["lab/roadmaps-service", LabRoadmapsServiceIcon],
	["lab/rovo", LabRovoIcon],
	["lab/rss-feed", LabRssFeedIcon],
	["lab/save", LabSaveIcon],
	["lab/screen-record", LabScreenRecordIcon],
	["lab/section", LabSectionIcon],
	["lab/service", LabServiceIcon],
	["lab/signature", LabSignatureIcon],
	["lab/signpost", LabSignpostIcon],
	["lab/skill", LabSkillIcon],
	["lab/skip", LabSkipIcon],
	["lab/skip-unskip", LabSkipUnskipIcon],
	["lab/sort-options", LabSortOptionsIcon],
	["lab/spaces", LabSpacesIcon],
	["lab/speedometer-left", LabSpeedometerLeftIcon],
	["lab/speedometer-right", LabSpeedometerRightIcon],
	["lab/speedometer-up", LabSpeedometerUpIcon],
	["lab/split-parallel", LabSplitParallelIcon],
	["lab/stamp", LabStampIcon],
	["lab/status-workflow-cancelled", LabStatusWorkflowCancelledIcon],
	["lab/status-workflow-danger", LabStatusWorkflowDangerIcon],
	["lab/status-workflow-in-progress", LabStatusWorkflowInProgressIcon],
	["lab/status-workflow-in-review", LabStatusWorkflowInReviewIcon],
	["lab/status-workflow-inactive", LabStatusWorkflowInactiveIcon],
	["lab/status-workflow-incomplete", LabStatusWorkflowIncompleteIcon],
	["lab/status-workflow-paused", LabStatusWorkflowPausedIcon],
	["lab/status-workflow-returned", LabStatusWorkflowReturnedIcon],
	["lab/status-workflow-scheduled", LabStatusWorkflowScheduledIcon],
	["lab/status-workflow-stopped", LabStatusWorkflowStoppedIcon],
	["lab/status-workflow-success", LabStatusWorkflowSuccessIcon],
	["lab/status-workflow-warning", LabStatusWorkflowWarningIcon],
	["lab/sticker", LabStickerIcon],
	["lab/studio", LabStudioIcon],
	["lab/suggested-edit", LabSuggestedEditIcon],
	["lab/sunset", LabSunsetIcon],
	["lab/survey", LabSurveyIcon],
	["lab/swap", LabSwapIcon],
	["lab/switch-case", LabSwitchCaseIcon],
	["lab/sync", LabSyncIcon],
	["lab/tab", LabTabIcon],
	["lab/table-row-limit", LabTableRowLimitIcon],
	["lab/takeout-container", LabTakeoutContainerIcon],
	["lab/talent", LabTalentIcon],
	["lab/teamwork-graph", LabTeamworkGraphIcon],
	["lab/telescope", LabTelescopeIcon],
	["lab/template", LabTemplateIcon],
	["lab/template-sync", LabTemplateSyncIcon],
	["lab/terminal", LabTerminalIcon],
	["lab/text-adjust-length", LabTextAdjustLengthIcon],
	["lab/text-audio-transcript", LabTextAudioTranscriptIcon],
	["lab/text-bold-italic", LabTextBoldItalicIcon],
	["lab/text-bold-italic-strikethrough", LabTextBoldItalicStrikethroughIcon],
	["lab/text-bold-italic-underline", LabTextBoldItalicUnderlineIcon],
	["lab/text-bold-italic-underline-strikethrough", LabTextBoldItalicUnderlineStrikethroughIcon],
	["lab/text-bold-strikethrough", LabTextBoldStrikethroughIcon],
	["lab/text-bold-underline", LabTextBoldUnderlineIcon],
	["lab/text-bold-underline-strikethrough", LabTextBoldUnderlineStrikethroughIcon],
	["lab/text-conclusion-add", LabTextConclusionAddIcon],
	["lab/text-cursor", LabTextCursorIcon],
	["lab/text-density-compress", LabTextDensityCompressIcon],
	["lab/text-density-expand", LabTextDensityExpandIcon],
	["lab/text-heading-five", LabTextHeadingFiveIcon],
	["lab/text-heading-four", LabTextHeadingFourIcon],
	["lab/text-heading-one", LabTextHeadingOneIcon],
	["lab/text-heading-six", LabTextHeadingSixIcon],
	["lab/text-heading-three", LabTextHeadingThreeIcon],
	["lab/text-heading-two", LabTextHeadingTwoIcon],
	["lab/text-introduction-add", LabTextIntroductionAddIcon],
	["lab/text-italic-strikethrough", LabTextItalicStrikethroughIcon],
	["lab/text-italic-underline", LabTextItalicUnderlineIcon],
	["lab/text-italic-underline-strikethrough", LabTextItalicUnderlineStrikethroughIcon],
	["lab/text-lengthen", LabTextLengthenIcon],
	["lab/text-letter-case", LabTextLetterCaseIcon],
	["lab/text-paragraph", LabTextParagraphIcon],
	["lab/text-rephrase", LabTextRephraseIcon],
	["lab/text-subscript", LabTextSubscriptIcon],
	["lab/text-superscript", LabTextSuperscriptIcon],
	["lab/text-underline-strikethrough", LabTextUnderlineStrikethroughIcon],
	["lab/ticket", LabTicketIcon],
	["lab/tidy", LabTidyIcon],
	["lab/variable", LabVariableIcon],
	["lab/vehicle-airplane", LabVehicleAirplaneIcon],
	["lab/vehicle-train", LabVehicleTrainIcon],
	["lab/video-captions-stylized", LabVideoCaptionsStylizedIcon],
	["lab/video-clip", LabVideoClipIcon],
	["lab/video-closed-captions", LabVideoClosedCaptionsIcon],
	["lab/video-closed-captions-filled", LabVideoClosedCaptionsFilledIcon],
	["lab/video-fast-forward", LabVideoFastForwardIcon],
	["lab/video-fast-forward-overlay", LabVideoFastForwardOverlayIcon],
	["lab/video-hd", LabVideoHdIcon],
	["lab/video-hd-filled", LabVideoHdFilledIcon],
	["lab/video-miniplayer", LabVideoMiniplayerIcon],
	["lab/video-overlay-tools", LabVideoOverlayToolsIcon],
	["lab/video-play-circle", LabVideoPlayCircleIcon],
	["lab/video-record", LabVideoRecordIcon],
	["lab/video-rewind", LabVideoRewindIcon],
	["lab/video-rewind-overlay", LabVideoRewindOverlayIcon],
	["lab/video-skip-backward-five", LabVideoSkipBackwardFiveIcon],
	["lab/video-skip-forward-five", LabVideoSkipForwardFiveIcon],
	["lab/video-strikethrough", LabVideoStrikethroughIcon],
	["lab/video-theater-mode", LabVideoTheaterModeIcon],
	["lab/video-timeline-clip-split", LabVideoTimelineClipSplitIcon],
	["lab/video-timeline-editor", LabVideoTimelineEditorIcon],
	["lab/video-watch-later-remove", LabVideoWatchLaterRemoveIcon],
	["lab/video-watch-later-saved", LabVideoWatchLaterSavedIcon],
	["lab/view-type-board-home", LabViewTypeBoardHomeIcon],
	["lab/view-type-card-home", LabViewTypeCardHomeIcon],
	["lab/view-type-table-home", LabViewTypeTableHomeIcon],
	["lab/views", LabViewsIcon],
	["lab/vulnerability", LabVulnerabilityIcon],
	["lab/wallet", LabWalletIcon],
	["lab/warning-outline", LabWarningOutlineIcon],
	["lab/webhook", LabWebhookIcon],
	["lab/welcome-feed", LabWelcomeFeedIcon],
	["lab/work-item-add", LabWorkItemAddIcon],
	["lab/workflow-controls", LabWorkflowControlsIcon],
	["lab/world", LabWorldIcon],
	["lab/wrench", LabWrenchIcon],
]);
