export const TOP_NAV_CONTROL_GAP_PX = 4;
export const TOP_NAV_ICON_BUTTON_SIZE_PX = 32;
export const TOP_NAV_COLLAPSED_CONTROL_STEP_PX =
	TOP_NAV_ICON_BUTTON_SIZE_PX + TOP_NAV_CONTROL_GAP_PX;

export const TOP_NAV_PADDING_PX = 12;
export const TOP_NAV_LEFT_SECTION_WIDTH_PX = 230;
export const ROVO_APP_SEPARATOR_LINE_OFFSET_PX = 320;
export const TOP_NAV_SIDEBAR_TOGGLE_SEPARATOR_GAP_PX = 12;
