import {
	DEFAULT_NEURAL_GRAPH_PARAMS,
	clampNeuralGraphParams,
	type NeuralGraphParams,
} from "@/components/arts/personal-graph/lib/neural-graph/params";

export const ROVO_GRAPH_COLORS = {
	blue: "var(--ds-icon-accent-blue)",
	default: "var(--ds-icon)",
	gray: "var(--ds-icon-accent-gray)",
	lime: "var(--ds-icon-accent-lime)",
	orange: "var(--ds-icon-accent-orange)",
	purple: "var(--ds-icon-accent-purple)",
	surface: "var(--ds-surface)",
} as const;

export const ROVO_GRAPH_DEFAULT_PARAMS: NeuralGraphParams = clampNeuralGraphParams({
	...DEFAULT_NEURAL_GRAPH_PARAMS,
	amplitude: 0.2,
	colorConcept: ROVO_GRAPH_COLORS.orange,
	colorEntity: ROVO_GRAPH_COLORS.lime,
	colorRaw: ROVO_GRAPH_COLORS.gray,
	colorSource: ROVO_GRAPH_COLORS.blue,
	colorSynthesis: ROVO_GRAPH_COLORS.purple,
	coneAngle: 92,
	depthZ: 42,
	edgeColor: ROVO_GRAPH_COLORS.gray,
	edgeHoverColor: ROVO_GRAPH_COLORS.gray,
	edgeOpacity: 0.2,
	edgeOpacityActive: 1,
	edgeSelectedColor: ROVO_GRAPH_COLORS.gray,
	edgeWidth: 2,
	frequency: 1.2,
	glowIntensity: 0,
	glowSize: 1,
	hoverScale: 1.5,
	labelMetaSize: 9,
	labelSize: 12,
	layoutShape: "radialCluster",
	maxVisibleNodes: 96,
	nodeColor: ROVO_GRAPH_COLORS.default,
	nodeOpacity: 1,
	nodeOpacityFocused: 1,
	nodeOpacityRelated: 1,
	nodeRadius: 0,
	nodeShape: "square",
	nodeSize: 4,
	octaves: 3,
	originMarkerColor: ROVO_GRAPH_COLORS.default,
	originMarkerSize: 12,
	originOffset: 0,
	originY: 0.52,
	perspective: 1000,
	radiusMax: 92,
	radiusMin: 20,
	rayColor: ROVO_GRAPH_COLORS.gray,
	rayElasticDamping: 24,
	rayElasticRadius: 96,
	rayElasticStrength: 26,
	rayElasticTension: 220,
	rayOpacity: 0.02,
	rayOriginY: 0.52,
	rayWidth: 2,
	radialArcAngle: 360,
	radialDepthCurve: 0.8,
	selectedScale: 1.5,
	showEdges: true,
	showLabels: true,
	showOriginMarker: true,
	showRays: true,
	showSignals: true,
	signalColor: ROVO_GRAPH_COLORS.default,
	signalFrequency: 0.5,
	signalGlowEnabled: false,
	signalLength: 0.5,
	signalOpacity: 1,
	signalWidth: 1,
	speed: 0.7,
	spread: 560,
	tiltX: -4,
	tiltZ: -6,
});
