export const SCRIBBLES_DEFAULT_SCALE = 16;
export const SCRIBBLES_DEFAULT_BASE_FREQUENCY = 0.02;
export const SCRIBBLES_DEFAULT_NUM_OCTAVES = 2;
export const SCRIBBLES_DEFAULT_SEED = 1;
export const SCRIBBLES_DEFAULT_INTERVAL_MS = 100;
export const SCRIBBLES_DEFAULT_AMOUNT = 0.5;
export const SCRIBBLES_DEFAULT_OFFSETS = [-0.02, 0.01, -0.01, 0.02] as const;
