// Single source of truth for the agent avatar set under `/public/avatar-agent`.
//
// Newly created agents — whether started from scratch or generated by AI — pick
// an avatar from this pool when no explicit avatar is supplied: a random one for
// throwaway from-scratch shells, or a deterministic one keyed on the agent's
// identity (`getDeterministicAgentAvatarSrc`) so every surface that renders the
// same agent agrees on the avatar. Avatars are grouped by agent family under
// `/avatar-agent/<group>/`, and every avatar in a family shares one brand color.
// The families are very different sizes (teamwork-agents alone holds ~44% of all
// avatars), so a flat uniform pick over files would land on the largest family's
// color (blue) far more often than the others. Both pickers balance by color
// family first (see below).

export const AGENT_AVATAR_GROUP_ACCENTS: Readonly<Record<string, string>> = {
	"dev-agents": "#82B536",
	"product-agents": "#BF63F3",
	"service-agents": "#FFC716",
	"strategy-agents": "#FCA700",
	"teamwork-agents": "#1868DB",
};

export const AGENT_AVATAR_FALLBACK_ACCENT = "#1868DB";

// Every avatar SVG available under `/public/avatar-agent`, grouped by family.
// Keep this list in sync with the files on disk.
export const AGENT_AVATAR_SRCS = [
	"/avatar-agent/dev-agents/basic-coding-agent-template.svg",
	"/avatar-agent/dev-agents/code-accessibility-checker.svg",
	"/avatar-agent/dev-agents/code-documentation-writer.svg",
	"/avatar-agent/dev-agents/code-observer-signalfx.svg",
	"/avatar-agent/dev-agents/code-planner.svg",
	"/avatar-agent/dev-agents/code-reviewer.svg",
	"/avatar-agent/dev-agents/code-standardizer.svg",
	"/avatar-agent/dev-agents/code-vulnerability-scanner-npm-yarn.svg",
	"/avatar-agent/dev-agents/deployment-summarizer.svg",
	"/avatar-agent/dev-agents/feature-flag-cleaner.svg",
	"/avatar-agent/dev-agents/migration-config-changer.svg",
	"/avatar-agent/dev-agents/pipeline-troubleshooter.svg",
	"/avatar-agent/dev-agents/unit-test-creator.svg",
	"/avatar-agent/dev-agents/wildcard-1.svg",
	"/avatar-agent/dev-agents/wildcard-2.svg",
	"/avatar-agent/dev-agents/wildcard-3.svg",
	"/avatar-agent/dev-agents/wildcard-4.svg",
	"/avatar-agent/product-agents/feedback-analyzer.svg",
	"/avatar-agent/product-agents/wildcard-1.svg",
	"/avatar-agent/product-agents/wildcard-2.svg",
	"/avatar-agent/product-agents/wildcard-3.svg",
	"/avatar-agent/product-agents/wildcard-4.svg",
	"/avatar-agent/product-agents/wildcard-5.svg",
	"/avatar-agent/product-agents/wildcard-6.svg",
	"/avatar-agent/service-agents/ops-guide.svg",
	"/avatar-agent/service-agents/rca-agent.svg",
	"/avatar-agent/service-agents/service-request-helper.svg",
	"/avatar-agent/service-agents/service-triage.svg",
	"/avatar-agent/service-agents/wildcard-1.svg",
	"/avatar-agent/service-agents/wildcard-2.svg",
	"/avatar-agent/service-agents/wildcard-3.svg",
	"/avatar-agent/service-agents/wildcard-4.svg",
	"/avatar-agent/service-agents/wildcard-5.svg",
	"/avatar-agent/strategy-agents/strategic-insight.svg",
	"/avatar-agent/strategy-agents/talent-finder.svg",
	"/avatar-agent/strategy-agents/wildcard-1.svg",
	"/avatar-agent/strategy-agents/wildcard-2.svg",
	"/avatar-agent/strategy-agents/wildcard-3.svg",
	"/avatar-agent/strategy-agents/wildcard-4.svg",
	"/avatar-agent/strategy-agents/wildcard-5.svg",
	"/avatar-agent/teamwork-agents/blocker-checker.svg",
	"/avatar-agent/teamwork-agents/brainstorm-facilitator.svg",
	"/avatar-agent/teamwork-agents/brand-guardian.svg",
	"/avatar-agent/teamwork-agents/bug-report-assistant.svg",
	"/avatar-agent/teamwork-agents/customer-insights.svg",
	"/avatar-agent/teamwork-agents/decision-director.svg",
	"/avatar-agent/teamwork-agents/diagram-creator.svg",
	"/avatar-agent/teamwork-agents/global-translator.svg",
	"/avatar-agent/teamwork-agents/jira-theme-analyzer.svg",
	"/avatar-agent/teamwork-agents/job-listing-assistant.svg",
	"/avatar-agent/teamwork-agents/meeting-insights-reporter.svg",
	"/avatar-agent/teamwork-agents/okr-generator.svg",
	"/avatar-agent/teamwork-agents/product-requirements-guide.svg",
	"/avatar-agent/teamwork-agents/progress-tracker.svg",
	"/avatar-agent/teamwork-agents/readiness-checker.svg",
	"/avatar-agent/teamwork-agents/release-notes-drafter.svg",
	"/avatar-agent/teamwork-agents/social-media-writer.svg",
	"/avatar-agent/teamwork-agents/team-recap.svg",
	"/avatar-agent/teamwork-agents/teamwork-coach.svg",
	"/avatar-agent/teamwork-agents/teamwork-trivia-host.svg",
	"/avatar-agent/teamwork-agents/transcript-insights-reporter.svg",
	"/avatar-agent/teamwork-agents/user-manual-writer.svg",
	"/avatar-agent/teamwork-agents/whtieboard-agent.svg",
	"/avatar-agent/teamwork-agents/wildcard-1.svg",
	"/avatar-agent/teamwork-agents/wildcard-2.svg",
	"/avatar-agent/teamwork-agents/wildcard-3.svg",
	"/avatar-agent/teamwork-agents/wildcard-4.svg",
	"/avatar-agent/teamwork-agents/work-item-planner.svg",
	"/avatar-agent/teamwork-agents/work-organizer.svg",
	"/avatar-agent/teamwork-agents/workflow-builder.svg",
] as const;

export type AgentAvatarSrc = (typeof AGENT_AVATAR_SRCS)[number];

const FALLBACK_AVATAR_SRC: AgentAvatarSrc = AGENT_AVATAR_SRCS[0];

/**
 * Returns the family group segment (e.g. "teamwork-agents") for an avatar path,
 * or `undefined` if the path doesn't match the expected shape.
 */
function getAgentAvatarGroup(avatarSrc: string): string | undefined {
	return avatarSrc.match(/\/avatar-agent\/([^/]+)\//u)?.[1];
}

/**
 * Returns the brand accent color for an avatar, derived from its family group in
 * the path. Falls back to the default accent for unrecognized paths.
 */
export function getAgentAvatarAccent(avatarSrc: string): string {
	const group = getAgentAvatarGroup(avatarSrc);
	return (group && AGENT_AVATAR_GROUP_ACCENTS[group]) || AGENT_AVATAR_FALLBACK_ACCENT;
}

// Avatars bucketed by family group, so a random pick can weight each color
// equally regardless of how many avatars a given family ships.
const AGENT_AVATAR_SRCS_BY_GROUP: ReadonlyArray<ReadonlyArray<AgentAvatarSrc>> = (() => {
	const groups = new Map<string, AgentAvatarSrc[]>();
	for (const src of AGENT_AVATAR_SRCS) {
		const group = getAgentAvatarGroup(src) ?? "";
		const bucket = groups.get(group);
		if (bucket) {
			bucket.push(src);
		} else {
			groups.set(group, [src]);
		}
	}
	return [...groups.values()];
})();

/**
 * Picks a random avatar with the color (family) chosen uniformly first, then a
 * uniformly random avatar within that family. This gives every brand color an
 * equal chance even though families ship very different numbers of avatars —
 * without it, the largest family (teamwork-agents / blue) would dominate.
 */
export function getRandomAgentAvatarSrc(): AgentAvatarSrc {
	const groupIndex = Math.floor(Math.random() * AGENT_AVATAR_SRCS_BY_GROUP.length);
	const group = AGENT_AVATAR_SRCS_BY_GROUP[groupIndex];
	if (!group || group.length === 0) {
		return FALLBACK_AVATAR_SRC;
	}
	const avatarIndex = Math.floor(Math.random() * group.length);
	return group[avatarIndex] ?? FALLBACK_AVATAR_SRC;
}

// Stable 32-bit string hash (FNV-1a). Used to derive a deterministic avatar from
// an agent's identity so two surfaces that independently render the same agent
// (the streamed result card and the persisted session entry) land on the exact
// same avatar — and therefore the same banner color — without sharing state.
function hashSeed(seed: string): number {
	let hash = 0x811c9dc5;
	for (let index = 0; index < seed.length; index += 1) {
		hash ^= seed.charCodeAt(index);
		hash = Math.imul(hash, 0x01000193);
	}
	return hash >>> 0;
}

/**
 * Deterministic counterpart to {@link getRandomAgentAvatarSrc}: the same `seed`
 * (typically an agent's `agentId`) always returns the same avatar, while still
 * balancing the choice by color family first so no single brand color dominates.
 *
 * Use this — not the random picker — whenever an agent that lacks an explicit
 * avatar is rendered in more than one place, so every surface agrees on the
 * avatar (and the family-derived banner color) for that identity. An empty seed
 * falls back to a stable default.
 */
export function getDeterministicAgentAvatarSrc(seed: string | null | undefined): AgentAvatarSrc {
	const normalizedSeed = seed?.trim();
	if (!normalizedSeed) {
		return FALLBACK_AVATAR_SRC;
	}
	const hash = hashSeed(normalizedSeed);
	const group = AGENT_AVATAR_SRCS_BY_GROUP[hash % AGENT_AVATAR_SRCS_BY_GROUP.length];
	if (!group || group.length === 0) {
		return FALLBACK_AVATAR_SRC;
	}
	// A second, independent shift keeps the within-family pick from correlating
	// with the family pick for short seeds.
	const avatarIndex = (hash >>> 8) % group.length;
	return group[avatarIndex] ?? FALLBACK_AVATAR_SRC;
}

// Cover-banner artwork for the agent profile/config cover, under
// `/public/smart-folders`. Every agent's cover picks one of these so the banners
// vary by design and color instead of all sharing one hardcoded artwork. The set
// is the 40 cleanly-named `<design>-<color>.svg` files: 8 designs × 5 colors
// (blue, gray, lime, orange, purple), evenly balanced so a flat pick already
// gives each color the same odds. The legacy `*_yellow.svg` files use
// inconsistent underscore naming and are intentionally excluded.
export const SMART_FOLDER_BANNER_SRCS = [
	"/smart-folders/abstract-blue.svg",
	"/smart-folders/abstract-gray.svg",
	"/smart-folders/abstract-lime.svg",
	"/smart-folders/abstract-orange.svg",
	"/smart-folders/abstract-purple.svg",
	"/smart-folders/abstract-2-blue.svg",
	"/smart-folders/abstract-2-gray.svg",
	"/smart-folders/abstract-2-lime.svg",
	"/smart-folders/abstract-2-orange.svg",
	"/smart-folders/abstract-2-purple.svg",
	"/smart-folders/cloud-blue.svg",
	"/smart-folders/cloud-gray.svg",
	"/smart-folders/cloud-lime.svg",
	"/smart-folders/cloud-orange.svg",
	"/smart-folders/cloud-purple.svg",
	"/smart-folders/default-blue.svg",
	"/smart-folders/default-gray.svg",
	"/smart-folders/default-lime.svg",
	"/smart-folders/default-orange.svg",
	"/smart-folders/default-purple.svg",
	"/smart-folders/default-2-blue.svg",
	"/smart-folders/default-2-gray.svg",
	"/smart-folders/default-2-lime.svg",
	"/smart-folders/default-2-orange.svg",
	"/smart-folders/default-2-purple.svg",
	"/smart-folders/dev-blue.svg",
	"/smart-folders/dev-gray.svg",
	"/smart-folders/dev-lime.svg",
	"/smart-folders/dev-orange.svg",
	"/smart-folders/dev-purple.svg",
	"/smart-folders/launch-blue.svg",
	"/smart-folders/launch-gray.svg",
	"/smart-folders/launch-lime.svg",
	"/smart-folders/launch-orange.svg",
	"/smart-folders/launch-purple.svg",
	"/smart-folders/meetings-blue.svg",
	"/smart-folders/meetings-gray.svg",
	"/smart-folders/meetings-lime.svg",
	"/smart-folders/meetings-orange.svg",
	"/smart-folders/meetings-purple.svg",
] as const;

export type SmartFolderBannerSrc = (typeof SMART_FOLDER_BANNER_SRCS)[number];

const FALLBACK_BANNER_SRC: SmartFolderBannerSrc = SMART_FOLDER_BANNER_SRCS[0];

/**
 * Deterministic banner picker, mirroring {@link getDeterministicAgentAvatarSrc}:
 * the same `seed` (typically an agent's `agentId`) always returns the same cover
 * banner, so every render of that agent agrees and the banner never flickers
 * between re-renders. The 40 banners are color-balanced, so a flat hash index is
 * enough — no family bucketing needed. An empty seed falls back to a stable
 * default.
 *
 * The hash is shifted (`>>> 16`) before indexing so an agent's banner pick does
 * not correlate with its avatar pick, even though both seed on the same id.
 */
export function getDeterministicAgentBannerSrc(seed: string | null | undefined): SmartFolderBannerSrc {
	const normalizedSeed = seed?.trim();
	if (!normalizedSeed) {
		return FALLBACK_BANNER_SRC;
	}
	const hash = hashSeed(normalizedSeed);
	const bannerIndex = (hash >>> 16) % SMART_FOLDER_BANNER_SRCS.length;
	return SMART_FOLDER_BANNER_SRCS[bannerIndex] ?? FALLBACK_BANNER_SRC;
}
