// Single source of truth for the agent avatar set under `/public/avatar-agent`.
//
// Newly created agents — whether started from scratch or generated by AI — pick
// an avatar from this pool when no explicit avatar is supplied: a random one for
// throwaway from-scratch shells, or a deterministic one keyed on the agent's
// identity (`getDeterministicAgentAvatarSrc`) so every surface that renders the
// same agent agrees on the avatar. Avatars are grouped by agent family under
// `/avatar-agent/<group>/`, and every avatar in a family shares one brand color.
// The families are very different sizes (teamwork-agents alone holds ~44% of all
// avatars), so a flat uniform pick over files would land on the largest family's
// color (blue) far more often than the others. Both pickers balance by color
// family first (see below).

export const AGENT_AVATAR_GROUP_ACCENTS: Readonly<Record<string, string>> = {
	"dev-agents": "#82B536",
	"product-agents": "#BF63F3",
	"service-agents": "#FFC716",
	"strategy-agents": "#FCA700",
	"teamwork-agents": "#1868DB",
};

export const AGENT_AVATAR_FALLBACK_ACCENT = "#1868DB";

// Every avatar SVG available under `/public/avatar-agent`, grouped by family.
// Keep this list in sync with the files on disk.
export const AGENT_AVATAR_SRCS = [
	"/avatar-agent/dev-agents/basic-coding-agent-template.svg",
	"/avatar-agent/dev-agents/code-accessibility-checker.svg",
	"/avatar-agent/dev-agents/code-documentation-writer.svg",
	"/avatar-agent/dev-agents/code-observer-signalfx.svg",
	"/avatar-agent/dev-agents/code-planner.svg",
	"/avatar-agent/dev-agents/code-reviewer.svg",
	"/avatar-agent/dev-agents/code-standardizer.svg",
	"/avatar-agent/dev-agents/code-vulnerability-scanner-npm-yarn.svg",
	"/avatar-agent/dev-agents/deployment-summarizer.svg",
	"/avatar-agent/dev-agents/feature-flag-cleaner.svg",
	"/avatar-agent/dev-agents/migration-config-changer.svg",
	"/avatar-agent/dev-agents/pipeline-troubleshooter.svg",
	"/avatar-agent/dev-agents/unit-test-creator.svg",
	"/avatar-agent/dev-agents/wildcard-1.svg",
	"/avatar-agent/dev-agents/wildcard-2.svg",
	"/avatar-agent/dev-agents/wildcard-3.svg",
	"/avatar-agent/dev-agents/wildcard-4.svg",
	"/avatar-agent/product-agents/feedback-analyzer.svg",
	"/avatar-agent/product-agents/wildcard-1.svg",
	"/avatar-agent/product-agents/wildcard-2.svg",
	"/avatar-agent/product-agents/wildcard-3.svg",
	"/avatar-agent/product-agents/wildcard-4.svg",
	"/avatar-agent/product-agents/wildcard-5.svg",
	"/avatar-agent/product-agents/wildcard-6.svg",
	"/avatar-agent/service-agents/ops-guide.svg",
	"/avatar-agent/service-agents/rca-agent.svg",
	"/avatar-agent/service-agents/service-request-helper.svg",
	"/avatar-agent/service-agents/service-triage.svg",
	"/avatar-agent/service-agents/wildcard-1.svg",
	"/avatar-agent/service-agents/wildcard-2.svg",
	"/avatar-agent/service-agents/wildcard-3.svg",
	"/avatar-agent/service-agents/wildcard-4.svg",
	"/avatar-agent/service-agents/wildcard-5.svg",
	"/avatar-agent/strategy-agents/strategic-insight.svg",
	"/avatar-agent/strategy-agents/talent-finder.svg",
	"/avatar-agent/strategy-agents/wildcard-1.svg",
	"/avatar-agent/strategy-agents/wildcard-2.svg",
	"/avatar-agent/strategy-agents/wildcard-3.svg",
	"/avatar-agent/strategy-agents/wildcard-4.svg",
	"/avatar-agent/strategy-agents/wildcard-5.svg",
	"/avatar-agent/teamwork-agents/blocker-checker.svg",
	"/avatar-agent/teamwork-agents/brainstorm-facilitator.svg",
	"/avatar-agent/teamwork-agents/brand-guardian.svg",
	"/avatar-agent/teamwork-agents/bug-report-assistant.svg",
	"/avatar-agent/teamwork-agents/customer-insights.svg",
	"/avatar-agent/teamwork-agents/decision-director.svg",
	"/avatar-agent/teamwork-agents/diagram-creator.svg",
	"/avatar-agent/teamwork-agents/global-translator.svg",
	"/avatar-agent/teamwork-agents/jira-theme-analyzer.svg",
	"/avatar-agent/teamwork-agents/job-listing-assistant.svg",
	"/avatar-agent/teamwork-agents/meeting-insights-reporter.svg",
	"/avatar-agent/teamwork-agents/okr-generator.svg",
	"/avatar-agent/teamwork-agents/product-requirements-guide.svg",
	"/avatar-agent/teamwork-agents/progress-tracker.svg",
	"/avatar-agent/teamwork-agents/readiness-checker.svg",
	"/avatar-agent/teamwork-agents/release-notes-drafter.svg",
	"/avatar-agent/teamwork-agents/social-media-writer.svg",
	"/avatar-agent/teamwork-agents/team-recap.svg",
	"/avatar-agent/teamwork-agents/teamwork-coach.svg",
	"/avatar-agent/teamwork-agents/teamwork-trivia-host.svg",
	"/avatar-agent/teamwork-agents/transcript-insights-reporter.svg",
	"/avatar-agent/teamwork-agents/user-manual-writer.svg",
	"/avatar-agent/teamwork-agents/whtieboard-agent.svg",
	"/avatar-agent/teamwork-agents/wildcard-1.svg",
	"/avatar-agent/teamwork-agents/wildcard-2.svg",
	"/avatar-agent/teamwork-agents/wildcard-3.svg",
	"/avatar-agent/teamwork-agents/wildcard-4.svg",
	"/avatar-agent/teamwork-agents/work-item-planner.svg",
	"/avatar-agent/teamwork-agents/work-organizer.svg",
	"/avatar-agent/teamwork-agents/workflow-builder.svg",
] as const;

export type AgentAvatarSrc = (typeof AGENT_AVATAR_SRCS)[number];

const FALLBACK_AVATAR_SRC: AgentAvatarSrc = AGENT_AVATAR_SRCS[0];
export const DEFAULT_AGENT_PROFILE_AVATAR_SRC = "/avatar-agent/teamwork-agents/blocker-checker.svg" satisfies AgentAvatarSrc;

/**
 * Returns the family group segment (e.g. "teamwork-agents") for an avatar path,
 * or `undefined` if the path doesn't match the expected shape.
 */
function getAgentAvatarGroup(avatarSrc: string): string | undefined {
	return avatarSrc.match(/\/avatar-agent\/([^/]+)\//u)?.[1];
}

/**
 * Returns the brand accent color for an avatar, derived from its family group in
 * the path. Falls back to the default accent for unrecognized paths.
 */
export function getAgentAvatarAccent(avatarSrc: string): string {
	const group = getAgentAvatarGroup(avatarSrc);
	return (group && AGENT_AVATAR_GROUP_ACCENTS[group]) || AGENT_AVATAR_FALLBACK_ACCENT;
}

// Avatars bucketed by family group, so a random pick can weight each color
// equally regardless of how many avatars a given family ships.
const AGENT_AVATAR_SRCS_BY_GROUP: ReadonlyArray<ReadonlyArray<AgentAvatarSrc>> = (() => {
	const groups = new Map<string, AgentAvatarSrc[]>();
	for (const src of AGENT_AVATAR_SRCS) {
		const group = getAgentAvatarGroup(src) ?? "";
		const bucket = groups.get(group);
		if (bucket) {
			bucket.push(src);
		} else {
			groups.set(group, [src]);
		}
	}
	return [...groups.values()];
})();

/**
 * Picks a random avatar with the color (family) chosen uniformly first, then a
 * uniformly random avatar within that family. This gives every brand color an
 * equal chance even though families ship very different numbers of avatars —
 * without it, the largest family (teamwork-agents / blue) would dominate.
 */
export function getRandomAgentAvatarSrc(): AgentAvatarSrc {
	const groupIndex = Math.floor(Math.random() * AGENT_AVATAR_SRCS_BY_GROUP.length);
	const group = AGENT_AVATAR_SRCS_BY_GROUP[groupIndex];
	if (!group || group.length === 0) {
		return FALLBACK_AVATAR_SRC;
	}
	const avatarIndex = Math.floor(Math.random() * group.length);
	return group[avatarIndex] ?? FALLBACK_AVATAR_SRC;
}

// Stable 32-bit string hash (FNV-1a). Used to derive a deterministic avatar from
// an agent's identity so two surfaces that independently render the same agent
// (the streamed result card and the persisted session entry) land on the exact
// same avatar — and therefore the same banner color — without sharing state.
function hashSeed(seed: string): number {
	let hash = 0x811c9dc5;
	for (let index = 0; index < seed.length; index += 1) {
		hash ^= seed.charCodeAt(index);
		hash = Math.imul(hash, 0x01000193);
	}
	return hash >>> 0;
}

/**
 * Deterministic counterpart to {@link getRandomAgentAvatarSrc}: the same `seed`
 * (typically an agent's `agentId`) always returns the same avatar, while still
 * balancing the choice by color family first so no single brand color dominates.
 *
 * Use this — not the random picker — whenever an agent that lacks an explicit
 * avatar is rendered in more than one place, so every surface agrees on the
 * avatar (and the family-derived banner color) for that identity. An empty seed
 * falls back to a stable default.
 */
export function getDeterministicAgentAvatarSrc(seed: string | null | undefined): AgentAvatarSrc {
	const normalizedSeed = seed?.trim();
	if (!normalizedSeed) {
		return FALLBACK_AVATAR_SRC;
	}
	const hash = hashSeed(normalizedSeed);
	const group = AGENT_AVATAR_SRCS_BY_GROUP[hash % AGENT_AVATAR_SRCS_BY_GROUP.length];
	if (!group || group.length === 0) {
		return FALLBACK_AVATAR_SRC;
	}
	// A second, independent shift keeps the within-family pick from correlating
	// with the family pick for short seeds.
	const avatarIndex = (hash >>> 8) % group.length;
	return group[avatarIndex] ?? FALLBACK_AVATAR_SRC;
}

// Cover-banner artwork for the agent profile/config cover, under
// `/public/smart-folders`. The banner's COLOR follows the agent's avatar family
// (so a green dev-agent gets a lime banner, a purple product-agent a purple one,
// etc. — see AGENT_AVATAR_GROUP_ACCENTS); only the DESIGN is randomized per agent.
// Grey is intentionally NEVER used — it reads as a disabled/empty state, so a
// banner always carries a brand color.
//
// Files are grouped by color subfolder (`/smart-folders/<color>/…`). Each color
// ships the same 8 designs in the same order, so the hashed design index maps
// consistently across colors.
const SMART_FOLDER_BANNER_SRCS_BY_COLOR = {
	blue: [
		"/smart-folders/blue/abstract-blue.svg",
		"/smart-folders/blue/abstract-2-blue.svg",
		"/smart-folders/blue/cloud-blue.svg",
		"/smart-folders/blue/default-blue.svg",
		"/smart-folders/blue/default-2-blue.svg",
		"/smart-folders/blue/dev-blue.svg",
		"/smart-folders/blue/launch-blue.svg",
		"/smart-folders/blue/meetings-blue.svg",
	],
	lime: [
		"/smart-folders/lime/abstract-lime.svg",
		"/smart-folders/lime/abstract-2-lime.svg",
		"/smart-folders/lime/cloud-lime.svg",
		"/smart-folders/lime/default-lime.svg",
		"/smart-folders/lime/default-2-lime.svg",
		"/smart-folders/lime/dev-lime.svg",
		"/smart-folders/lime/launch-lime.svg",
		"/smart-folders/lime/meetings-lime.svg",
	],
	orange: [
		"/smart-folders/orange/abstract-orange.svg",
		"/smart-folders/orange/abstract-2-orange.svg",
		"/smart-folders/orange/cloud-orange.svg",
		"/smart-folders/orange/default-orange.svg",
		"/smart-folders/orange/default-2-orange.svg",
		"/smart-folders/orange/dev-orange.svg",
		"/smart-folders/orange/launch-orange.svg",
		"/smart-folders/orange/meetings-orange.svg",
	],
	purple: [
		"/smart-folders/purple/abstract-purple.svg",
		"/smart-folders/purple/abstract-2-purple.svg",
		"/smart-folders/purple/cloud-purple.svg",
		"/smart-folders/purple/default-purple.svg",
		"/smart-folders/purple/default-2-purple.svg",
		"/smart-folders/purple/dev-purple.svg",
		"/smart-folders/purple/launch-purple.svg",
		"/smart-folders/purple/meetings-purple.svg",
	],
	yellow: [
		"/smart-folders/yellow/abstract-yellow.svg",
		"/smart-folders/yellow/abstract-2-yellow.svg",
		"/smart-folders/yellow/cloud-yellow.svg",
		"/smart-folders/yellow/default-yellow.svg",
		"/smart-folders/yellow/default-2-yellow.svg",
		"/smart-folders/yellow/dev-yellow.svg",
		"/smart-folders/yellow/launch-yellow.svg",
		"/smart-folders/yellow/meetings-yellow.svg",
	],
} as const satisfies Record<string, readonly string[]>;

export type SmartFolderBannerColor = keyof typeof SMART_FOLDER_BANNER_SRCS_BY_COLOR;
export type SmartFolderBannerSrc = (typeof SMART_FOLDER_BANNER_SRCS_BY_COLOR)[SmartFolderBannerColor][number];

// Maps each avatar family to its banner color, parallel to
// AGENT_AVATAR_GROUP_ACCENTS. Grey has no entry — it is never a banner color.
const AGENT_AVATAR_GROUP_BANNER_COLORS: Readonly<Record<string, SmartFolderBannerColor>> = {
	"dev-agents": "lime",
	"product-agents": "purple",
	"service-agents": "yellow",
	"strategy-agents": "orange",
	"teamwork-agents": "blue",
};

export const FALLBACK_BANNER_COLOR: SmartFolderBannerColor = "blue";

/**
 * Returns the banner color for an avatar, derived from its family group so the
 * cover banner matches the avatar's brand color. Falls back to blue for
 * unrecognized paths.
 */
export function getAgentBannerColor(avatarSrc: string | null | undefined): SmartFolderBannerColor {
	const group = avatarSrc ? getAgentAvatarGroup(avatarSrc) : undefined;
	return (group && AGENT_AVATAR_GROUP_BANNER_COLORS[group]) || FALLBACK_BANNER_COLOR;
}

/**
 * Picks the cover banner for an agent: the COLOR comes from `avatarSrc`'s family
 * (so the banner matches the avatar's brand color, never grey), and the DESIGN is
 * chosen deterministically so the same agent always shows the same banner and it
 * never flickers between renders.
 *
 * The design seed folds in BOTH `avatarSrc` and `seed` (typically the agent's
 * `agentId`). Seeding on the avatar too means swapping the avatar — which also
 * changes the color — moves the design as well, instead of leaving one design
 * recolored across every color (the `agentId` alone is fixed while editing a
 * single agent, so it can't vary the design as the avatar changes). The `agentId`
 * term still gives two agents that share an avatar distinct designs.
 *
 * `seed` falls back to `avatarSrc` when an id isn't available; an empty seed
 * lands on the first design. The hash is shifted (`>>> 16`) before indexing so
 * the design pick doesn't correlate with the avatar pick that seeds on the same id.
 */
export function getDeterministicAgentBannerSrc(
	avatarSrc: string | null | undefined,
	seed: string | null | undefined,
): SmartFolderBannerSrc {
	const color = getAgentBannerColor(avatarSrc);
	const designs = SMART_FOLDER_BANNER_SRCS_BY_COLOR[color];
	const normalizedSeed = seed?.trim() || avatarSrc?.trim();
	if (!normalizedSeed) {
		return designs[0];
	}
	const designSeed = `${avatarSrc?.trim() ?? ""}|${normalizedSeed}`;
	const hash = hashSeed(designSeed);
	const designIndex = (hash >>> 16) % designs.length;
	return designs[designIndex] ?? designs[0];
}

/** Resolves the exact banner used by Agent Profile cards, including their fallback avatar. */
export function getAgentProfileBannerSrc(avatarSrc: string | null | undefined): SmartFolderBannerSrc {
	const resolvedAvatarSrc = avatarSrc?.trim() || DEFAULT_AGENT_PROFILE_AVATAR_SRC;
	return getDeterministicAgentBannerSrc(resolvedAvatarSrc, resolvedAvatarSrc);
}
