import {
	GUIColorInput,
	GUIColorList,
	GUIControl,
	GUIImageInput,
	GUIPanel,
	GUIPercentControl,
	GUIRgbaColorInput,
	GUISection,
	GUISegmentedControl,
	GUISelect,
	GUISwatchGroup,
	GUITextInput,
	GUIToggle,
} from "@/components/utils/gui-components";

export {
	type GUIColorInputProps,
	type GUIColorListProps,
	type GUIControlProps,
	type GUIImageInputProps,
	type GUIPanelProps,
	type GUIPercentControlProps,
	type GUIRgbaColorInputProps,
	type GUISectionProps,
	type GUISegmentedControlProps,
	type GUISegmentedOption,
	type GUISelectOption,
	type GUISelectProps,
	type GUISwatchGroupProps,
	type GUISwatchOption,
	type GUITextInputProps,
	type GUIToggleProps,
	useGUIValueKeys,
} from "@/components/utils/gui-components";

export const GUI = {
	ColorInput: GUIColorInput,
	ColorList: GUIColorList,
	Control: GUIControl,
	ImageInput: GUIImageInput,
	Panel: GUIPanel,
	PercentControl: GUIPercentControl,
	RgbaColorInput: GUIRgbaColorInput,
	Section: GUISection,
	SegmentedControl: GUISegmentedControl,
	Select: GUISelect,
	SwatchGroup: GUISwatchGroup,
	TextInput: GUITextInput,
	Toggle: GUIToggle,
} as const;
