export interface Contact {
	id: string;
	name: string;
	email: string;
	company: string;
	role: string;
	status: "active" | "inactive" | "lead";
	phone: string;
	avatarUrl: string;
	createdAt: string;
	lastContacted: string;
	notes: string;
}

export const CONTACTS: Contact[] = [
	{
		id: "c-001",
		name: "Olivia Chen",
		email: "olivia.chen@acmecorp.com",
		company: "Acme Corp",
		role: "VP of Engineering",
		status: "active",
		phone: "+1 (415) 555-0101",
		avatarUrl: "/avatar-user/andrea-wilson/color/asow-teamwork-blue.png",
		createdAt: "2025-09-14",
		lastContacted: "2026-03-28",
		notes: "Interested in enterprise plan. Follow up after Q1 review.",
	},
	{
		id: "c-002",
		name: "Marcus Johnson",
		email: "m.johnson@globexinc.com",
		company: "Globex Inc",
		role: "Product Manager",
		status: "active",
		phone: "+1 (212) 555-0182",
		avatarUrl: "/avatar-user/andrew-park/color/asow-teamwork-blue.png",
		createdAt: "2025-11-02",
		lastContacted: "2026-03-25",
		notes: "Evaluating our platform against competitors.",
	},
	{
		id: "c-003",
		name: "Priya Patel",
		email: "priya@initech.io",
		company: "Initech",
		role: "CTO",
		status: "lead",
		phone: "+44 20 7946 0958",
		avatarUrl: "/avatar-user/annie-clare/color/asow-teamwork-blue.png",
		createdAt: "2026-01-18",
		lastContacted: "2026-03-20",
		notes: "Met at SaaStr conference. Requested a demo for her team.",
	},
	{
		id: "c-004",
		name: "James O'Brien",
		email: "james.obrien@wayneent.com",
		company: "Wayne Enterprises",
		role: "Director of IT",
		status: "active",
		phone: "+1 (312) 555-0147",
		avatarUrl: "/avatar-user/austin-lambert/color/asow-teamwork-blue.png",
		createdAt: "2025-07-22",
		lastContacted: "2026-03-15",
		notes: "Renewed annual contract. Upsell opportunity for additional seats.",
	},
	{
		id: "c-005",
		name: "Sofia Rodriguez",
		email: "sofia.r@umbrellacorp.com",
		company: "Umbrella Corp",
		role: "Head of Operations",
		status: "inactive",
		phone: "+1 (305) 555-0193",
		avatarUrl: "/avatar-user/avery/color/asow-teamwork-blue.png",
		createdAt: "2025-04-10",
		lastContacted: "2025-12-01",
		notes: "Paused engagement due to budget freeze. Re-engage in Q2.",
	},
	{
		id: "c-006",
		name: "Liam Nakamura",
		email: "liam.n@starkind.com",
		company: "Stark Industries",
		role: "Engineering Manager",
		status: "active",
		phone: "+1 (650) 555-0126",
		avatarUrl: "/avatar-user/bradley-phillips/color/asow-teamwork-blue.png",
		createdAt: "2025-10-30",
		lastContacted: "2026-03-27",
		notes: "Power user. Contributing feedback to our beta program.",
	},
	{
		id: "c-007",
		name: "Amara Okafor",
		email: "amara@oscorptech.com",
		company: "Oscorp Technologies",
		role: "Senior Developer",
		status: "lead",
		phone: "+234 1 555 0134",
		avatarUrl: "/avatar-user/brian-lin/color/asow-teamwork-blue.png",
		createdAt: "2026-02-05",
		lastContacted: "2026-03-22",
		notes: "Exploring API integrations. Sent technical documentation.",
	},
	{
		id: "c-008",
		name: "Ethan Moreau",
		email: "ethan.m@cyberdyne.co",
		company: "Cyberdyne Systems",
		role: "VP of Sales",
		status: "active",
		phone: "+33 1 55 50 01 42",
		avatarUrl: "/avatar-user/chloe-lee/color/asow-teamwork-blue.png",
		createdAt: "2025-08-19",
		lastContacted: "2026-03-26",
		notes: "Large deal in pipeline. Decision expected by end of month.",
	},
	{
		id: "c-009",
		name: "Hannah Kim",
		email: "hannah.kim@lexcorp.com",
		company: "LexCorp",
		role: "Data Analyst",
		status: "inactive",
		phone: "+82 2 555 0189",
		avatarUrl: "/avatar-user/christine-sanchez/color/asow-teamwork-blue.png",
		createdAt: "2025-06-03",
		lastContacted: "2025-11-15",
		notes: "Churned after trial. Cited missing reporting features.",
	},
	{
		id: "c-010",
		name: "Daniel Fischer",
		email: "d.fischer@hooli.xyz",
		company: "Hooli",
		role: "Chief of Staff",
		status: "active",
		phone: "+49 30 555 0167",
		avatarUrl: "/avatar-user/darius-pavri/color/asow-teamwork-blue.png",
		createdAt: "2025-12-11",
		lastContacted: "2026-03-29",
		notes: "Signed annual deal. Onboarding scheduled for next week.",
	},
	{
		id: "c-011",
		name: "Zara Ali",
		email: "zara.ali@piedinc.com",
		company: "Pied Piper",
		role: "Frontend Lead",
		status: "lead",
		phone: "+92 21 555 0112",
		avatarUrl: "/avatar-user/david-hsieh/color/asow-teamwork-blue.png",
		createdAt: "2026-03-01",
		lastContacted: "2026-03-18",
		notes: "Inbound from website. Interested in team collaboration features.",
	},
	{
		id: "c-012",
		name: "Ryan Torres",
		email: "ryan.t@massivdyn.com",
		company: "Massive Dynamic",
		role: "Solutions Architect",
		status: "active",
		phone: "+1 (408) 555-0155",
		avatarUrl: "/avatar-user/ali/color/asow-teamwork-blue.png",
		createdAt: "2025-05-27",
		lastContacted: "2026-03-24",
		notes: "Technical champion internally. Helping drive adoption.",
	},
	{
		id: "c-013",
		name: "Elena Volkov",
		email: "elena.v@tyrell.co",
		company: "Tyrell Corporation",
		role: "Program Manager",
		status: "inactive",
		phone: "+7 495 555 0178",
		avatarUrl: "/avatar-user/aoife-burke/color/asow-teamwork-blue.png",
		createdAt: "2025-03-14",
		lastContacted: "2025-10-20",
		notes: "Organization restructuring. Contact after new fiscal year.",
	},
	{
		id: "c-014",
		name: "Noah Williams",
		email: "noah.w@wonkaindustries.com",
		company: "Wonka Industries",
		role: "Head of Product",
		status: "active",
		phone: "+1 (617) 555-0199",
		avatarUrl: "/avatar-user/ash/color/asow-teamwork-blue.png",
		createdAt: "2025-09-08",
		lastContacted: "2026-03-30",
		notes: "Expanding usage to marketing team. Needs SSO setup.",
	},
	{
		id: "c-015",
		name: "Ines Dubois",
		email: "ines.d@soylentcorp.com",
		company: "Soylent Corp",
		role: "DevOps Engineer",
		status: "lead",
		phone: "+33 4 55 50 01 36",
		avatarUrl: "/avatar-user/aspen/color/asow-teamwork-blue.png",
		createdAt: "2026-02-20",
		lastContacted: "2026-03-12",
		notes: "Interested in CI/CD integration capabilities.",
	},
];
