import type { LockscreenLocation } from "./locations";

export const PRESET_CITIES: ReadonlyArray<LockscreenLocation> = [
	{
		id: "sydney",
		name: "Sydney",
		code: "SYD",
		region: "Australia",
		timezone: "Australia/Sydney",
		latitude: -33.8688,
		longitude: 151.2093,
	},
	{
		id: "tokyo",
		name: "Tokyo",
		code: "TYO",
		region: "Japan",
		timezone: "Asia/Tokyo",
		latitude: 35.6762,
		longitude: 139.6503,
	},
	{
		id: "new-york",
		name: "New York",
		code: "NYC",
		region: "United States",
		timezone: "America/New_York",
		latitude: 40.7128,
		longitude: -74.006,
	},
	{
		id: "london",
		name: "London",
		code: "LDN",
		region: "United Kingdom",
		timezone: "Europe/London",
		latitude: 51.5074,
		longitude: -0.1278,
	},
	{
		id: "paris",
		name: "Paris",
		code: "PAR",
		region: "France",
		timezone: "Europe/Paris",
		latitude: 48.8566,
		longitude: 2.3522,
	},
	{
		id: "berlin",
		name: "Berlin",
		code: "BER",
		region: "Germany",
		timezone: "Europe/Berlin",
		latitude: 52.52,
		longitude: 13.405,
	},
	{
		id: "san-francisco",
		name: "San Francisco",
		code: "SF",
		region: "United States",
		timezone: "America/Los_Angeles",
		latitude: 37.7749,
		longitude: -122.4194,
	},
	{
		id: "los-angeles",
		name: "Los Angeles",
		code: "LA",
		region: "United States",
		timezone: "America/Los_Angeles",
		latitude: 34.0522,
		longitude: -118.2437,
	},
	{
		id: "singapore",
		name: "Singapore",
		code: "SG",
		region: "Singapore",
		timezone: "Asia/Singapore",
		latitude: 1.3521,
		longitude: 103.8198,
	},
	{
		id: "dubai",
		name: "Dubai",
		code: "DXB",
		region: "UAE",
		timezone: "Asia/Dubai",
		latitude: 25.2048,
		longitude: 55.2708,
	},
	{
		id: "mumbai",
		name: "Mumbai",
		code: "BOM",
		region: "India",
		timezone: "Asia/Kolkata",
		latitude: 19.076,
		longitude: 72.8777,
	},
	{
		id: "toronto",
		name: "Toronto",
		code: "YYZ",
		region: "Canada",
		timezone: "America/Toronto",
		latitude: 43.6532,
		longitude: -79.3832,
	},
	{
		id: "mexico-city",
		name: "Mexico City",
		code: "MEX",
		region: "Mexico",
		timezone: "America/Mexico_City",
		latitude: 19.4326,
		longitude: -99.1332,
	},
	{
		id: "sao-paulo",
		name: "São Paulo",
		code: "GRU",
		region: "Brazil",
		timezone: "America/Sao_Paulo",
		latitude: -23.5505,
		longitude: -46.6333,
	},
	{
		id: "seoul",
		name: "Seoul",
		code: "SEL",
		region: "South Korea",
		timezone: "Asia/Seoul",
		latitude: 37.5665,
		longitude: 126.978,
	},
	{
		id: "shanghai",
		name: "Shanghai",
		code: "SHA",
		region: "China",
		timezone: "Asia/Shanghai",
		latitude: 31.2304,
		longitude: 121.4737,
	},
	{
		id: "bangkok",
		name: "Bangkok",
		code: "BKK",
		region: "Thailand",
		timezone: "Asia/Bangkok",
		latitude: 13.7563,
		longitude: 100.5018,
	},
	{
		id: "cairo",
		name: "Cairo",
		code: "CAI",
		region: "Egypt",
		timezone: "Africa/Cairo",
		latitude: 30.0444,
		longitude: 31.2357,
	},
	{
		id: "istanbul",
		name: "Istanbul",
		code: "IST",
		region: "Turkey",
		timezone: "Europe/Istanbul",
		latitude: 41.0082,
		longitude: 28.9784,
	},
	{
		id: "moscow",
		name: "Moscow",
		code: "MOW",
		region: "Russia",
		timezone: "Europe/Moscow",
		latitude: 55.7558,
		longitude: 37.6173,
	},
	{
		id: "rome",
		name: "Rome",
		code: "ROM",
		region: "Italy",
		timezone: "Europe/Rome",
		latitude: 41.9028,
		longitude: 12.4964,
	},
	{
		id: "amsterdam",
		name: "Amsterdam",
		code: "AMS",
		region: "Netherlands",
		timezone: "Europe/Amsterdam",
		latitude: 52.3676,
		longitude: 4.9041,
	},
	{
		id: "cape-town",
		name: "Cape Town",
		code: "CPT",
		region: "South Africa",
		timezone: "Africa/Johannesburg",
		latitude: -33.9249,
		longitude: 18.4241,
	},
	{
		id: "buenos-aires",
		name: "Buenos Aires",
		code: "BUE",
		region: "Argentina",
		timezone: "America/Argentina/Buenos_Aires",
		latitude: -34.6037,
		longitude: -58.3816,
	},
	{
		id: "auckland",
		name: "Auckland",
		code: "AKL",
		region: "New Zealand",
		timezone: "Pacific/Auckland",
		latitude: -36.8485,
		longitude: 174.7633,
	},
	{
		id: "kuala-lumpur",
		name: "Kuala Lumpur",
		code: "KL",
		region: "Malaysia",
		timezone: "Asia/Kuala_Lumpur",
		latitude: 3.139,
		longitude: 101.6869,
	},
];

export const DEFAULT_PRESET_CITY = PRESET_CITIES[0];

const DEFAULT_PRESET_CITY_IDS = [
	"sydney",
	"san-francisco",
	"tokyo",
	"kuala-lumpur",
] as const;

export const DEFAULT_PRESET_CITIES: ReadonlyArray<LockscreenLocation> =
	DEFAULT_PRESET_CITY_IDS.map((id) => {
		const city = PRESET_CITIES.find((c) => c.id === id);
		if (!city) {
			throw new Error(`DEFAULT_PRESET_CITIES: missing preset city "${id}"`);
		}
		return city;
	});
