import {
	InlineCitation,
	InlineCitationCard,
	InlineCitationCardBody,
	InlineCitationCardTrigger,
	InlineCitationCarousel,
	InlineCitationCarouselContent,
	InlineCitationCarouselHeader,
	InlineCitationCarouselIndex,
	InlineCitationCarouselItem,
	InlineCitationCarouselNext,
	InlineCitationCarouselPrev,
	InlineCitationQuote,
	InlineCitationSource,
	InlineCitationText,
} from "@/components/ui-custom/inline-citation";

const SOURCES = [
	{
		title: "React Documentation",
		url: "https://react.dev/learn",
		description:
			"React lets you build user interfaces out of individual pieces called components.",
		quote:
			"React uses a virtual DOM to efficiently update and render just the right components when your data changes.",
	},
	{
		title: "MDN Web Docs",
		url: "https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model",
		description:
			"The Document Object Model (DOM) is a programming interface for web documents.",
	},
	{
		title: "Wikipedia — Virtual DOM",
		url: "https://en.wikipedia.org/wiki/Virtual_DOM",
		description:
			"A virtual DOM is an in-memory representation of real DOM elements generated by React components.",
	},
];

export default function InlineCitationDemo() {
	return <InlineCitationDemoWithCarousel />;
}

export function InlineCitationDemoBasic() {
	return (
		<p className="max-w-lg text-sm leading-relaxed text-text">
			<InlineCitation>
				<InlineCitationText>React uses a virtual DOM</InlineCitationText>
				<InlineCitationCard>
					<InlineCitationCardTrigger
						sources={["https://react.dev", "https://developer.mozilla.org"]}
					/>
				</InlineCitationCard>
			</InlineCitation>{" "}
			to efficiently update only the parts of the page that have changed.
		</p>
	);
}

export function InlineCitationDemoWithCarousel() {
	return (
		<p className="max-w-lg text-sm leading-relaxed text-text">
			<InlineCitation>
				<InlineCitationText>React uses a virtual DOM</InlineCitationText>
				<InlineCitationCard>
					<InlineCitationCardTrigger
						sources={SOURCES.map((s) => s.url)}
					/>
					<InlineCitationCardBody>
						<InlineCitationCarousel>
							<InlineCitationCarouselHeader>
								<InlineCitationCarouselPrev />
								<InlineCitationCarouselIndex />
								<InlineCitationCarouselNext />
							</InlineCitationCarouselHeader>
							<InlineCitationCarouselContent>
								{SOURCES.map((source) => (
									<InlineCitationCarouselItem key={source.url}>
										<InlineCitationSource
											title={source.title}
											url={source.url}
											description={source.description}
										/>
										{source.quote ? (
											<InlineCitationQuote>
												{source.quote}
											</InlineCitationQuote>
										) : null}
									</InlineCitationCarouselItem>
								))}
							</InlineCitationCarouselContent>
						</InlineCitationCarousel>
					</InlineCitationCardBody>
				</InlineCitationCard>
			</InlineCitation>{" "}
			to efficiently update only the parts of the page that have changed.
		</p>
	);
}

export function InlineCitationDemoMultiple() {
	return (
		<p className="max-w-lg text-sm leading-relaxed text-text">
			<InlineCitation>
				<InlineCitationText>
					Server Components run on the server
				</InlineCitationText>
				<InlineCitationCard>
					<InlineCitationCardTrigger sources={["https://react.dev/reference/rsc/server-components"]} />
					<InlineCitationCardBody>
						<InlineCitationCarousel>
							<InlineCitationCarouselContent>
								<InlineCitationCarouselItem>
									<InlineCitationSource
										title="React Server Components"
										url="https://react.dev/reference/rsc/server-components"
										description="Server Components are a new type of Component that renders ahead of time, before bundling."
									/>
								</InlineCitationCarouselItem>
							</InlineCitationCarouselContent>
						</InlineCitationCarousel>
					</InlineCitationCardBody>
				</InlineCitationCard>
			</InlineCitation>{" "}
			and send pre-rendered HTML to the client, while{" "}
			<InlineCitation>
				<InlineCitationText>
					Client Components hydrate on the browser
				</InlineCitationText>
				<InlineCitationCard>
					<InlineCitationCardTrigger
						sources={[
							"https://react.dev/reference/rsc/use-client",
							"https://nextjs.org/docs/app/building-your-application/rendering/client-components",
						]}
					/>
					<InlineCitationCardBody>
						<InlineCitationCarousel>
							<InlineCitationCarouselHeader>
								<InlineCitationCarouselPrev />
								<InlineCitationCarouselIndex />
								<InlineCitationCarouselNext />
							</InlineCitationCarouselHeader>
							<InlineCitationCarouselContent>
								<InlineCitationCarouselItem>
									<InlineCitationSource
										title="'use client' Directive"
										url="https://react.dev/reference/rsc/use-client"
										description="Marks source files whose components execute on the client."
									/>
								</InlineCitationCarouselItem>
								<InlineCitationCarouselItem>
									<InlineCitationSource
										title="Next.js Client Components"
										url="https://nextjs.org/docs/app/building-your-application/rendering/client-components"
										description="Client Components allow you to write interactive UI that is prerendered on the server."
									/>
								</InlineCitationCarouselItem>
							</InlineCitationCarouselContent>
						</InlineCitationCarousel>
					</InlineCitationCardBody>
				</InlineCitationCard>
			</InlineCitation>{" "}
			to add interactivity.
		</p>
	);
}

export function InlineCitationDemoSingleSource() {
	return (
		<p className="max-w-lg text-sm leading-relaxed text-text">
			<InlineCitation>
				<InlineCitationText>
					TypeScript adds static type checking to JavaScript
				</InlineCitationText>
				<InlineCitationCard>
					<InlineCitationCardTrigger sources={["https://www.typescriptlang.org"]} />
					<InlineCitationCardBody>
						<InlineCitationCarousel>
							<InlineCitationCarouselContent>
								<InlineCitationCarouselItem>
									<InlineCitationSource
										title="TypeScript Documentation"
										url="https://www.typescriptlang.org"
										description="TypeScript is a strongly typed programming language that builds on JavaScript."
									/>
									<InlineCitationQuote>
										TypeScript adds additional syntax to JavaScript to support a tighter integration with your editor.
									</InlineCitationQuote>
								</InlineCitationCarouselItem>
							</InlineCitationCarouselContent>
						</InlineCitationCarousel>
					</InlineCitationCardBody>
				</InlineCitationCard>
			</InlineCitation>
			, catching errors at compile time rather than at runtime.
		</p>
	);
}
