model = "gpt-5.4"
model_context_window = 1000000
model_auto_compact_token_limit = 900000
model_provider = "openai-no-ws"
model_reasoning_effort = "high"
sandbox_mode = "danger-full-access"
approval_policy = "never"
web_search = "live"
check_for_update_on_startup = true
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"
approvals_reviewer = "guardian_subagent"

[features]
unified_exec = true
shell_snapshot = true
personality = true
multi_agent = true
prevent_idle_sleep = true
responses_websockets = false
responses_websockets_v2 = false
fast_mode = true
js_repl = true
guardian_approval = true
tui_app_server = false

[sandbox_workspace_write]
network_access = true

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.context7]
startup_timeout_sec = 60
command = "npx"
args = [ "-y", "@upstash/context7-mcp" ]

[mcp_servers.context7.env]
CONTEXT7_API_KEY = "ctx7sk-88e60957-b10f-4ab7-a836-3e2028d5ebb8"

[mcp_servers.shadcn]
startup_timeout_sec = 60
command = "npx"
args = [ "shadcn@latest", "mcp" ]

[mcp_servers.ads-mcp]
url = "https://mcp.atlassian.com/v1/ads/public/mcp"

[mcp_servers.motion]
startup_timeout_sec = 60
command = "npx"
args = [ "-y", "https://api.motion.dev/registry.tgz?package=motion-studio-mcp&version=latest&token=fc0a8c2295343956b76bd070a01a9863c7a11d012c3983c9a7bf9720642e239f" ]

[mcp_servers.playwright]
startup_timeout_sec = 60
command = "npx"
args = [ "@playwright/mcp@latest", "--browser", "chromium" ]
enabled = false

[mcp_servers.paper]
enabled = false
url = "http://127.0.0.1:29979/mcp"

[mcp_servers.react-grab-mcp]
command = "npx"
args = [ "-y", "@react-grab/mcp", "--stdio" ]

[model_providers.openai-no-ws]
name = "OpenAI (HTTPS only)"
wire_api = "responses"
requires_openai_auth = true
supports_websockets = false

[projects."/Users/esoh"]
trust_level = "trusted"

[projects."/Users/esoh/Documents/Labs/VPK-rovodev"]
trust_level = "trusted"

[projects."/Users/esoh/Downloads/craft-agents-oss-main"]
trust_level = "trusted"

[projects."/Users/esoh/Documents/Labs/chatbot-main"]
trust_level = "trusted"

[projects."/Users/esoh/Documents/Labs/cmux-main/cmux"]
trust_level = "trusted"

[tui]
status_line = [ "model-with-reasoning", "current-dir", "context-window-size", "context-used", "used-tokens" ]

[apps.connector_76869538009648d5b282a4bb21c3d157]
enabled = false
